// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/spec/go/common

package common

#Display: {
	name?:        string @go(Name)
	description?: string @go(Description)
}
