"""Compatibility wrapper for context seed phase handlers.

The full implementation lives in ``startd8.contractors.context_seed.core``.
This module preserves the legacy import path.
"""

from __future__ import annotations

from startd8.contractors.context_seed.core import (  # noqa: F401
    ContextSeedHandlers,
    DesignPhaseHandler,
    EditModeClassification,
    FinalizePhaseHandler,
    HandlerConfig,
    ImplementPhaseHandler,
    IntegratePhaseHandler,
    OTelIntegrationListener,
    PerFileMode,
    PlanPhaseHandler,
    ReviewPhaseHandler,
    ScaffoldPhaseHandler,
    SeedTask,
    SeedTaskUnit,
    TestPhaseHandler,
    _build_provenance_links,
    _capture_task_span_context,
    _coerce_optional_float,
    _compute_ccd_task_metadata,
    _compute_design_results_hash,
    _compute_gen_file_hash,
    _detect_cross_file_edges,
    _ensure_context_loaded,
    _extract_complexity_signals,
    _extract_design_target_files,
    _extract_referenced_elements,
    _extract_structural_delta,
    _format_review_prompt,
    _get_review_template,
    _infer_path_prefix,
    _load_enriched_seed,
    _log_context_completeness,
    _log_task_boundary_complete,
    _log_task_boundary_start,
    _log_task_timing,
    _normalize_target_path,
    _parse_tasks,
    _set_default_complexity_metadata,
    _topological_sort,
    _track_onboarding_consumption,
    build_shared_file_manifest,
    compute_critical_path_tasks,
    compute_lane_to_file_mapping,
)

__all__ = [
    "ContextSeedHandlers",
    "DesignPhaseHandler",
    "EditModeClassification",
    "FinalizePhaseHandler",
    "HandlerConfig",
    "ImplementPhaseHandler",
    "IntegratePhaseHandler",
    "OTelIntegrationListener",
    "PerFileMode",
    "PlanPhaseHandler",
    "ReviewPhaseHandler",
    "ScaffoldPhaseHandler",
    "SeedTask",
    "SeedTaskUnit",
    "TestPhaseHandler",
    "_build_provenance_links",
    "_capture_task_span_context",
    "_coerce_optional_float",
    "_compute_ccd_task_metadata",
    "_compute_design_results_hash",
    "_compute_gen_file_hash",
    "_detect_cross_file_edges",
    "_ensure_context_loaded",
    "_extract_complexity_signals",
    "_extract_design_target_files",
    "_extract_referenced_elements",
    "_extract_structural_delta",
    "_format_review_prompt",
    "_get_review_template",
    "_infer_path_prefix",
    "_load_enriched_seed",
    "_log_context_completeness",
    "_log_task_boundary_complete",
    "_log_task_boundary_start",
    "_log_task_timing",
    "_normalize_target_path",
    "_parse_tasks",
    "_set_default_complexity_metadata",
    "_topological_sort",
    "_track_onboarding_consumption",
    "build_shared_file_manifest",
    "compute_critical_path_tasks",
    "compute_lane_to_file_mapping",
]
