"""
Feature Queue - Manages the ordered list of features to develop and integrate.

The feature queue ensures:
1. Features are processed in dependency order
2. Each feature's status is tracked (pending, developing, integrating, complete)
3. Failed integrations block dependent features
4. The queue can be persisted and resumed

This module is now part of startd8-sdk and works without ContextCore.
"""

import json
from dataclasses import asdict, dataclass, field
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional

from startd8.utils.file_operations import atomic_write_json
from ..logging_config import get_logger

logger = get_logger(__name__)


class FeatureStatus(Enum):
    """Status of a feature in the queue."""

    PENDING = "pending"  # Not yet started
    DEVELOPING = "developing"  # Lead contractor is generating code
    GENERATED = "generated"  # Code generated, ready for integration
    INTEGRATING = "integrating"  # Integration in progress
    CHECKPOINT = "checkpoint"  # Running integration checkpoints
    COMPLETE = "complete"  # Fully integrated and validated
    FAILED = "failed"  # Integration failed, needs attention
    BLOCKED = "blocked"  # Blocked by failed dependency


@dataclass
class FeatureSpec:
    """Specification for a feature to be developed."""

    id: str
    name: str
    description: str = ""
    dependencies: List[str] = field(default_factory=list)
    target_files: List[str] = field(default_factory=list)
    status: FeatureStatus = FeatureStatus.PENDING
    started_at: Optional[str] = None
    completed_at: Optional[str] = None
    error_message: Optional[str] = None
    integration_attempts: int = 0
    generated_files: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)
    copy_source_task_id: Optional[str] = None
    copy_source_file: Optional[str] = None

    def to_dict(self) -> Dict:
        """Convert to dictionary for JSON serialization."""
        d = asdict(self)
        d["status"] = self.status.value
        return d

    @classmethod
    def from_dict(cls, d: Dict) -> "FeatureSpec":
        """Create from dictionary."""
        d = d.copy()
        d["status"] = FeatureStatus(d.get("status", "pending"))
        # Tolerate older state files that lack 'metadata'.
        # Note: cls(**d) will raise TypeError on unknown keys — acceptable
        # because state files are always self-generated by to_dict().
        d.setdefault("metadata", {})
        d.setdefault("copy_source_task_id", None)
        d.setdefault("copy_source_file", None)
        return cls(**d)


class FeatureQueue:
    """
    Manages the ordered queue of features to develop and integrate.

    Key responsibilities:
    1. Track feature status through the pipeline
    2. Enforce dependency ordering
    3. Block dependent features when integration fails
    4. Persist state for resume capability

    Example:
        queue = FeatureQueue()
        queue.add_feature("feat-1", "Add auth", description="OAuth2 implementation")
        queue.add_feature("feat-2", "Add logout", dependencies=["feat-1"])

        feature = queue.get_next_feature()
        queue.start_feature(feature.id)
        # ... do work ...
        queue.complete_feature(feature.id)
    """

    def __init__(
        self,
        state_file: Optional[Path] = None,
        auto_save: bool = True,
        project_root: Optional[Path] = None,
    ):
        """
        Initialize the feature queue.

        Args:
            state_file: Path to state file for persistence
            auto_save: Whether to auto-save on changes
            project_root: Project root for default state file location
        """
        self.features: Dict[str, FeatureSpec] = {}
        self.order: List[str] = []  # Processing order
        self.auto_save = auto_save
        # F-AC-03: Runtime-only skip set — features in this set are skipped by
        # get_next_feature() without mutating their persisted status.
        self._skip_ids: set = set()

        # Determine state file location
        if state_file:
            self.state_file = state_file
        elif project_root:
            self.state_file = project_root / ".prime_contractor_state.json"
        else:
            self.state_file = Path.cwd() / ".prime_contractor_state.json"

        # Load existing state if available
        if self.state_file.exists():
            self.load_state()

    def add_feature(
        self,
        feature_id: str,
        name: str,
        description: str = "",
        dependencies: Optional[List[str]] = None,
        target_files: Optional[List[str]] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> FeatureSpec:
        """
        Add a feature to the queue, preserving loaded state.

        If the feature already exists with a non-pending status (e.g. loaded
        from a persisted state file), its status, timestamps, generated files,
        and error information are preserved.  Metadata (name, description,
        dependencies, target_files) is updated in case the caller changed them.

        This allows workflow scripts to declare their full feature queue on
        every invocation without destroying resume state.

        Args:
            feature_id: Unique identifier for the feature.
            name: Human-readable feature name.
            description: Feature description for code generation prompts.
            dependencies: List of feature IDs this feature depends on.
            target_files: List of target file paths for code generation.
            metadata: Optional dict of enrichment metadata (requirements_text,
                _enrichment, artifact_types_addressed, etc.). Merged into
                existing metadata on update, set directly on new features.
        """
        existing = self.features.get(feature_id)
        if existing and existing.status != FeatureStatus.PENDING:
            # Preserve progress state; update metadata that may have changed.
            existing.name = name
            existing.description = description
            existing.dependencies = dependencies or []
            existing.target_files = target_files or []
            # Merge new metadata into existing (additive, not destructive)
            if metadata:
                existing.metadata.update(metadata)
            if feature_id not in self.order:
                self.order.append(feature_id)
            if self.auto_save:
                self.save_state()
            return existing

        # New feature or existing pending feature — create fresh spec.
        spec = FeatureSpec(
            id=feature_id,
            name=name,
            description=description,
            dependencies=dependencies or [],
            target_files=target_files or [],
            metadata=metadata or {},
        )

        self.features[feature_id] = spec
        if feature_id not in self.order:
            self.order.append(feature_id)

        if self.auto_save:
            self.save_state()

        return spec

    def add_features_from_plan(self, plan: Dict) -> List[FeatureSpec]:
        """
        Add features from an integration plan.

        This allows importing features from the lead contractor's
        generated backlog.

        Args:
            plan: Integration plan with "files" list

        Returns:
            List of added features
        """
        added = []

        for item in plan.get("files", []):
            feature_name = item.get("feature", "unknown")
            feature_id = feature_name.replace(" ", "_").lower()

            if feature_id not in self.features:
                spec = self.add_feature(
                    feature_id=feature_id,
                    name=feature_name,
                    target_files=[item.get("target", "")],
                )
                spec.generated_files = [item.get("source", "")]
                spec.status = FeatureStatus.GENERATED
                added.append(spec)

        return added

    def add_features_from_seed(self, seed_path: "Path | str") -> List[FeatureSpec]:
        """
        Add features from a context-seed JSON file (plan-ingestion output).

        Bridges the seed task schema to flat FeatureSpec fields:
          seed task_id          → FeatureSpec.id
          seed title            → FeatureSpec.name
          seed config.task_description → FeatureSpec.description
          seed config.context.target_files → FeatureSpec.target_files
          seed depends_on       → FeatureSpec.dependencies

        Uses add_feature() internally so resume state is preserved
        (won't overwrite completed features on re-invocation).

        Args:
            seed_path: Path to the context-seed JSON file.

        Returns:
            List of added/updated FeatureSpec objects.
        """
        import json as _json
        from pathlib import Path as _Path

        path = _Path(seed_path)
        data = _json.loads(path.read_text(encoding="utf-8"))
        tasks = data.get("tasks", [])

        # Build plan-level feature_id → task_id mapping so we can resolve
        # copy_source_task_id references that use plan IDs (e.g. F-001a)
        # instead of seed task IDs (e.g. PI-001).
        plan_id_to_task_id: Dict[str, str] = {}
        for task in tasks:
            task_id = task.get("task_id", task.get("id", ""))
            ctx = task.get("config", {}).get("context", {})
            plan_fid = ctx.get("feature_id")
            if plan_fid and task_id:
                plan_id_to_task_id[plan_fid] = task_id

        added = []
        for task in tasks:
            task_id = task.get("task_id", task.get("id", ""))
            title = task.get("title", "(untitled)")
            config = task.get("config", {})
            description = config.get("task_description", "")
            context = config.get("context", {})
            target_files = context.get("target_files", [])
            dependencies = task.get("depends_on", [])

            spec = self.add_feature(
                feature_id=task_id,
                name=title,
                description=description,
                dependencies=dependencies,
                target_files=target_files,
            )
            # AC-R5: Bridge pre-enriched copy_source_task_id from seed context.
            # Resolve plan-level IDs (F-xxx) to task IDs (PI-xxx) so
            # _handle_file_copy can find the predecessor in the queue.
            copy_src_id = context.get("copy_source_task_id")
            if copy_src_id and spec.copy_source_task_id is None:
                resolved = plan_id_to_task_id.get(copy_src_id, copy_src_id)
                if resolved != copy_src_id:
                    logger.debug(
                        "Resolved copy_source_task_id '%s' → '%s' for task '%s'",
                        copy_src_id, resolved, task_id,
                    )
                spec.copy_source_task_id = resolved
                copy_src_file = context.get("copy_source_file")
                if copy_src_file:
                    spec.copy_source_file = copy_src_file

            # Mottainai Gap 9: preserve seed enrichment through the queue
            # boundary so prime gen_context can access it downstream.
            enrichment = task.get("_enrichment", {})
            config = task.get("config", {})
            context = config.get("context", {}) if isinstance(config, dict) else {}
            artifact_types = context.get("artifact_types_addressed", [])
            design_sections = context.get("design_doc_sections", [])
            estimated_loc = context.get("estimated_loc")
            # IMP-P2: bridge requirements_text from seed through metadata
            requirements_text = config.get("requirements_text", "")
            meta: Dict[str, Any] = {}
            if requirements_text:
                meta["requirements_text"] = requirements_text
            if enrichment:
                meta["_enrichment"] = enrichment
            if artifact_types:
                meta["artifact_types_addressed"] = artifact_types
            if design_sections:
                meta["design_doc_sections"] = design_sections
            if estimated_loc is not None:
                meta["estimated_loc"] = estimated_loc
            if meta:
                spec.metadata.update(meta)
            added.append(spec)

        return added

    def get_feature(self, feature_id: str) -> Optional[FeatureSpec]:
        """Look up a feature by ID."""
        return self.features.get(feature_id)

    def set_skip_ids(self, skip_ids: set) -> None:
        """Set feature IDs to skip during processing (F-AC-03).

        Unlike the prior approach of mutating status to COMPLETE, this
        sets a runtime-only skip set that is not persisted to the state
        file, preventing state corruption across runs.

        Args:
            skip_ids: Set of feature IDs to skip in get_next_feature().
        """
        self._skip_ids = set(skip_ids)
        if skip_ids:
            logger.info(
                "Skip set applied: %d feature(s) excluded from processing",
                len(skip_ids),
            )

    def get_next_feature(self) -> Optional[FeatureSpec]:
        """
        Get the next feature to process.

        Returns the first feature that:
        1. Is in PENDING or GENERATED status
        2. Has all dependencies completed (or dependency is in _skip_ids
           and considered satisfied for filter purposes)
        3. Is not in the runtime _skip_ids set
        """
        for feature_id in self.order:
            feature = self.features.get(feature_id)
            if not feature:
                continue

            # F-AC-03: Skip filtered-out features without mutating status
            if feature_id in self._skip_ids:
                continue

            # Skip completed or failed features
            if feature.status in (
                FeatureStatus.COMPLETE,
                FeatureStatus.FAILED,
                FeatureStatus.BLOCKED,
            ):
                continue

            # Check dependencies — skipped dependencies are treated as
            # satisfied so filtered features can still run if their deps
            # are outside the filter set.
            deps_met = True
            for dep_id in feature.dependencies:
                if dep_id in self._skip_ids:
                    continue  # Skipped dep treated as satisfied
                dep = self.features.get(dep_id)
                if not dep or dep.status != FeatureStatus.COMPLETE:
                    deps_met = False
                    break

            if deps_met and feature.status in (
                FeatureStatus.PENDING,
                FeatureStatus.GENERATED,
            ):
                return feature

        return None

    def start_feature(self, feature_id: str) -> bool:
        """Mark a feature as started (developing)."""
        feature = self.features.get(feature_id)
        if not feature:
            return False

        feature.status = FeatureStatus.DEVELOPING
        feature.started_at = datetime.now().isoformat()

        if self.auto_save:
            self.save_state()

        return True

    def mark_generated(self, feature_id: str, generated_files: List[str]) -> bool:
        """Mark a feature as having generated code."""
        feature = self.features.get(feature_id)
        if not feature:
            return False

        feature.status = FeatureStatus.GENERATED
        feature.generated_files = generated_files

        if self.auto_save:
            self.save_state()

        return True

    def start_integration(self, feature_id: str) -> bool:
        """Mark a feature as being integrated."""
        feature = self.features.get(feature_id)
        if not feature:
            return False

        feature.status = FeatureStatus.INTEGRATING
        feature.integration_attempts += 1

        if self.auto_save:
            self.save_state()

        return True

    def complete_feature(self, feature_id: str) -> bool:
        """Mark a feature as complete."""
        feature = self.features.get(feature_id)
        if not feature:
            return False

        feature.status = FeatureStatus.COMPLETE
        feature.completed_at = datetime.now().isoformat()

        if self.auto_save:
            self.save_state()

        return True

    def fail_feature(self, feature_id: str, error_message: str) -> bool:
        """Mark a feature as failed."""
        feature = self.features.get(feature_id)
        if not feature:
            return False

        feature.status = FeatureStatus.FAILED
        feature.error_message = error_message

        # Block dependent features
        self._block_dependents(feature_id)

        if self.auto_save:
            self.save_state()

        return True

    def _block_dependents(self, failed_feature_id: str):
        """Block all features that depend on a failed feature."""
        for feature_id, feature in self.features.items():
            if failed_feature_id in feature.dependencies:
                if feature.status == FeatureStatus.PENDING:
                    feature.status = FeatureStatus.BLOCKED
                    feature.error_message = (
                        f"Blocked by failed dependency: {failed_feature_id}"
                    )

    def get_status_summary(self) -> Dict[str, int]:
        """Get a summary of feature statuses."""
        summary = {status.value: 0 for status in FeatureStatus}

        for feature in self.features.values():
            summary[feature.status.value] += 1

        return summary

    def get_progress(self) -> float:
        """Get overall progress as a percentage.

        When a skip set is active (F-AC-03), only non-skipped features
        count toward the denominator so progress reflects the filtered
        subset, not the full queue.
        """
        if not self.features:
            return 0.0

        if self._skip_ids:
            active = [
                f for fid, f in self.features.items()
                if fid not in self._skip_ids
            ]
            if not active:
                return 100.0
            completed = sum(
                1 for f in active if f.status == FeatureStatus.COMPLETE
            )
            return (completed / len(active)) * 100
        else:
            completed = sum(
                1 for f in self.features.values()
                if f.status == FeatureStatus.COMPLETE
            )
            return (completed / len(self.features)) * 100

    def save_state(self):
        """Save queue state to file (atomic write to prevent corruption)."""
        state = {
            "features": {fid: f.to_dict() for fid, f in self.features.items()},
            "order": self.order,
            "saved_at": datetime.now().isoformat(),
        }

        try:
            atomic_write_json(Path(self.state_file), state, indent=2)
        except Exception:
            logger.warning(
                "Atomic write failed for %s, falling back to direct write",
                self.state_file,
                exc_info=True,
            )
            with open(self.state_file, "w") as f:
                json.dump(state, f, indent=2)

    def load_state(self) -> bool:
        """Load queue state from file."""
        try:
            with open(self.state_file, "r") as f:
                state = json.load(f)

            self.features = {
                fid: FeatureSpec.from_dict(fd)
                for fid, fd in state.get("features", {}).items()
            }
            self.order = state.get("order", [])

            return True
        except (json.JSONDecodeError, IOError):
            return False

    def reset(self):
        """Reset the queue to initial state."""
        for feature in self.features.values():
            feature.status = FeatureStatus.PENDING
            feature.started_at = None
            feature.completed_at = None
            feature.error_message = None
            feature.integration_attempts = 0

        if self.auto_save:
            self.save_state()

    def print_status(self):
        """Log current queue status."""
        summary = self.get_status_summary()
        progress = self.get_progress()

        lines = [
            "",
            "=" * 70,
            "FEATURE QUEUE STATUS",
            "=" * 70,
            f"\nProgress: {progress:.1f}% ({summary['complete']}/{len(self.features)} features)",
            f"  Pending: {summary['pending']}",
            f"  Developing: {summary['developing']}",
            f"  Generated: {summary['generated']}",
            f"  Integrating: {summary['integrating']}",
            f"  Complete: {summary['complete']}",
            f"  Failed: {summary['failed']}",
            f"  Blocked: {summary['blocked']}",
            "\nFeature Details:",
        ]

        for feature_id in self.order:
            feature = self.features.get(feature_id)
            if not feature:
                continue

            icon = {
                FeatureStatus.PENDING: "○",
                FeatureStatus.DEVELOPING: "◐",
                FeatureStatus.GENERATED: "◑",
                FeatureStatus.INTEGRATING: "◕",
                FeatureStatus.CHECKPOINT: "◔",
                FeatureStatus.COMPLETE: "●",
                FeatureStatus.FAILED: "✗",
                FeatureStatus.BLOCKED: "⊘",
            }.get(feature.status, "?")

            lines.append(f"  {icon} {feature.name} ({feature.status.value})")
            if feature.error_message:
                lines.append(f"      Error: {feature.error_message}")
            if feature.dependencies:
                lines.append(f"      Depends on: {', '.join(feature.dependencies)}")

        logger.info("\n".join(lines))
