# Copyright 2026 StartD8 Contributors
# SPDX-License-Identifier: LicenseRef-Equitable-Use-1.0

"""Domain alert renderer (M1) — the strangler that closes the declared-threshold gap.

The existing ``generate_alert_rules`` (RED convention alerts: latency/error/availability) is
**untouched** — this is a *separate, additive* renderer. It turns each :class:`ObservabilitySpec`
signal carrying a declarative ``threshold`` (or a raw PromQL ``expr``) into an **active** Prometheus
rule, which is exactly the gap the old ``_domain_alert_todo_block`` left as commented-out stubs
(``generators.py``: *"no manifest threshold, so not emitted as active rules"*).

Because this path is new and additive, RED output is byte-identical by construction (FR-OAA-10):
nothing here runs unless an ``ObservabilitySpec`` is provided.
"""

from __future__ import annotations

import re
from typing import Any, Dict, List, Optional

import yaml

from .artifact_generator_models import ArtifactResult, DerivationTrace
from .spec import ObservabilitySpec, Signal

_SOURCE = "observability.yaml alerting.metric_thresholds"


def _alert_name(metric: str) -> str:
    """``household_chore_overdue`` → ``HouseholdChoreOverdue`` (PascalCase, alnum-segmented)."""
    parts = [p for p in re.split(r"[^0-9a-zA-Z]+", metric) if p]
    return "".join(p[:1].upper() + p[1:] for p in parts) or "Alert"


def _expr_for(sig: Signal) -> Optional[str]:
    """The PromQL the rule fires on: a raw ``expr`` escape hatch wins; else ``<name> <op> <value>``
    from the declarative threshold; ``None`` when the signal carries neither (panel-only)."""
    if sig.expr:
        return sig.expr
    if sig.threshold is not None:
        t = sig.threshold
        return f"{sig.name} {t.op} {t.value}"
    return None


def render_domain_alert_rules(spec: ObservabilitySpec, project_id: str = "domain") -> ArtifactResult:
    """Render one Prometheus alert file with an **active rule per alertable signal**.

    Alertable = the signal has a declarative ``threshold`` or a raw ``expr``. Signals with neither
    are skipped (they are panel-only). When nothing is alertable, the result is an honest ``skipped``
    (never an empty active file).
    """
    rules: List[Dict[str, Any]] = []
    for sig in spec.signals:
        expr = _expr_for(sig)
        if expr is None:
            continue
        severity = sig.threshold.severity if sig.threshold else "warning"
        for_duration = sig.threshold.for_ if sig.threshold else "0m"
        rules.append(
            {
                "alert": _alert_name(sig.name),
                "expr": expr,
                "for": for_duration,
                "labels": {"severity": severity},
                "annotations": {"summary": expr, "source": _SOURCE},
            }
        )

    output_path = f"alerts/{project_id}-domain-alerts.yaml"
    if not rules:
        return ArtifactResult(
            artifact_type="alert_rule",
            service_id=project_id,
            output_path=output_path,
            status="skipped",
            error_message="no alertable signals (no thresholds or exprs declared)",
        )

    content_dict = {"groups": [{"name": f"{project_id}.domain", "rules": rules}]}
    header = (
        "# Generated by startd8 observability artifact generator (domain alerts, M1)\n"
        f"# Source: {_SOURCE} — {len(rules)} active rule(s)\n\n"
    )
    body = yaml.dump(content_dict, default_flow_style=False, sort_keys=False)
    return ArtifactResult(
        artifact_type="alert_rule",
        service_id=project_id,
        output_path=output_path,
        status="generated",
        content=header + body,
        derivations=[
            DerivationTrace(
                field="domain_alert_rules",
                source=_SOURCE,
                transformation=f"{len(rules)} thresholded/expr signal(s) → active alert rule(s)",
                tier="manifest",
            )
        ],
    )
