# Copyright 2026 Force Multiplier Labs
# SPDX-License-Identifier: LicenseRef-FSL-1.1-ALv2

"""Backend-pluggable render seam (container-o11y FR-13, ADR-008).

Derivation computes backend-neutral *intent*; a :class:`BackendAdapter` renders it to the
mechanism the target cluster actually runs:

* ``operator`` — Prometheus-Operator CRDs (``ServiceMonitor`` / ``PrometheusRule``), for clusters
  running prometheus-operator. This is today's behaviour, reproduced byte-for-byte.
* ``agent`` — Alloy scrape config (+ Mimir ruler rules + Grafana JSON, added as consumers land),
  for Alloy/LGTM stacks like o11y-dev that have no operator.

Step 1 introduces the seam on the one true operator-CRD render point (the ServiceMonitor scrape);
the alert path already emits a backend-neutral rule-group and dashboards are already two-stage, so
only ``render_scrape`` needs an adapter today. render_rules/render_dashboard are added when the
agent backend's consumers (the infra intent) are wired (Step 2).
"""

from __future__ import annotations

import abc
from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, Optional

import yaml


class RenderBackend(Enum):
    """The mechanism a target cluster runs for scrape/rules/dashboards."""

    OPERATOR = "operator"   # prometheus-operator CRDs
    AGENT = "agent"         # Grafana Alloy + Mimir ruler + Grafana JSON


@dataclass(frozen=True)
class ScrapeIntent:
    """Backend-neutral description of a /metrics scrape target."""

    name: str
    transport: str = ""
    namespace: Optional[str] = None
    scrape_interval: str = "30s"
    port: str = "metrics"
    path: str = "/metrics"
    selector_labels: Dict[str, str] = field(default_factory=dict)


@dataclass(frozen=True)
class RenderedArtifact:
    """A rendered artifact: where it goes and its complete serialized content."""

    output_path: str
    content: str


class BackendAdapter(abc.ABC):
    """Renders backend-neutral intent to one cluster mechanism."""

    backend: RenderBackend

    @abc.abstractmethod
    def render_scrape(self, intent: ScrapeIntent, derivation_comment: str) -> RenderedArtifact:
        """Render a scrape target for ``intent``."""


class OperatorAdapter(BackendAdapter):
    """Prometheus-Operator backend — emits a ``ServiceMonitor`` CRD.

    Byte-for-byte identical to the pre-seam ``generate_service_monitor`` output (guarded by the
    existing service_monitor golden tests + a direct parity test).
    """

    backend = RenderBackend.OPERATOR

    def render_scrape(self, intent: ScrapeIntent, derivation_comment: str) -> RenderedArtifact:
        metadata: Dict[str, object] = {
            "name": intent.name,
            "labels": {
                "app": intent.name,
                "managed-by": "startd8-observability",
            },
        }
        if intent.namespace:
            metadata["namespace"] = intent.namespace
        doc: Dict[str, object] = {
            "apiVersion": "monitoring.coreos.com/v1",
            "kind": "ServiceMonitor",
            "metadata": metadata,
            "spec": {
                "selector": {"matchLabels": {"app": intent.name}},
                "endpoints": [
                    {"port": intent.port, "path": intent.path, "interval": intent.scrape_interval}
                ],
            },
        }
        header = (
            f"# Generated by startd8 observability artifact generator\n"
            f"# Service: {intent.name} (transport: {intent.transport})\n"
            f"{derivation_comment}\n\n"
        )
        return RenderedArtifact(
            output_path=f"service-monitors/{intent.name}-servicemonitor.yaml",
            content=header + yaml.dump(doc, default_flow_style=False, sort_keys=False),
        )


class AgentAdapter(BackendAdapter):
    """Grafana Alloy backend — emits a ``prometheus.scrape`` River block (no operator needed)."""

    backend = RenderBackend.AGENT

    def render_scrape(self, intent: ScrapeIntent, derivation_comment: str) -> RenderedArtifact:
        # Alloy uses // comments; carry the same provenance lines, re-prefixed.
        comment = "\n".join(
            "//" + line[1:] if line.startswith("#") else ("// " + line if line else "//")
            for line in derivation_comment.splitlines()
        )
        address = f"{intent.name}:80"  # service DNS; port name resolved by the Service
        block = (
            f"// Generated by startd8 observability artifact generator\n"
            f"// Service: {intent.name} (transport: {intent.transport})\n"
            f"{comment}\n\n"
            f'prometheus.scrape "{intent.name}" {{\n'
            f'  targets         = [{{"__address__" = "{address}", "app" = "{intent.name}"}}]\n'
            f'  metrics_path    = "{intent.path}"\n'
            f'  scrape_interval = "{intent.scrape_interval}"\n'
            f"  forward_to      = [prometheus.remote_write.default.receiver]\n"
            f"}}\n"
        )
        return RenderedArtifact(
            output_path=f"alloy/{intent.name}-scrape.alloy",
            content=block,
        )


_ADAPTERS: Dict[RenderBackend, BackendAdapter] = {
    RenderBackend.OPERATOR: OperatorAdapter(),
    RenderBackend.AGENT: AgentAdapter(),
}


def get_adapter(backend: RenderBackend = RenderBackend.OPERATOR) -> BackendAdapter:
    """Return the adapter for ``backend`` (defaults to the operator = today's behaviour)."""
    return _ADAPTERS[backend]
