# Copyright 2026 Force Multiplier Labs
# SPDX-License-Identifier: LicenseRef-FSL-1.1-ALv2

"""Domain dashboard renderer (E1) — the M1 pattern applied to dashboards.

Mirrors ``alert_renderer.render_domain_alert_rules``: turns each :class:`ObservabilitySpec` signal
into a Grafana panel (a ``DashboardSpec`` compatible with ``DashboardCreatorWorkflow`` / ``/dbrd-cr8r``),
so the **same** ``observability.yaml`` that drives the domain *alerts* also drives a domain
*dashboard* — closing the "declare once → alerts **and** dashboards" gap (E1).

Separate + additive: the existing per-service ``generate_dashboard_spec`` path (which reads
``onboarding-metadata`` ``declared_metrics``) is **untouched**. This is a project-level dashboard from
the ``ObservabilitySpec`` — the single unification point the artifact abstraction is built around.
"""

from __future__ import annotations

from typing import Any, Dict, List

import yaml

from .artifact_generator_models import ArtifactResult, DerivationTrace
from .spec import ObservabilitySpec

_SOURCE = "observability.yaml alerting.metric_thresholds"
_COLS, _PANEL_W, _PANEL_H = 2, 12, 8  # two panels per row on the 24-col Grafana grid


def _title(metric: str) -> str:
    """``household_chore_overdue`` → ``Household Chore Overdue``."""
    words = metric.replace(".", " ").replace("_", " ").replace("-", " ").split()
    return " ".join(w.capitalize() for w in words) or metric


def render_domain_dashboard(spec: ObservabilitySpec, project_id: str = "domain") -> ArtifactResult:
    """Render one ``DashboardSpec`` with a timeseries panel per signal.

    A thresholded signal charts its **metric** (``signal.name``) with a threshold line at the value
    (severity-coloured); an expr-only signal charts its raw ``expr``. Empty ⇒ an honest ``skipped``.
    """
    panels: List[Dict[str, Any]] = []
    for i, sig in enumerate(spec.signals):
        # chart the METRIC (so the threshold reads as a line); expr-only signals chart their expr.
        expr = sig.name if sig.threshold is not None else (sig.expr or sig.name)
        panel: Dict[str, Any] = {
            "type": "timeseries",
            "title": _title(sig.name),
            "expr": expr,
            "gridPos": {
                "h": _PANEL_H, "w": _PANEL_W,
                "x": (i % _COLS) * _PANEL_W, "y": (i // _COLS) * _PANEL_H,
            },
        }
        if sig.threshold is not None:
            color = "red" if sig.threshold.severity == "critical" else "orange"
            panel["thresholds"] = [
                {"color": "green", "value": None},                       # baseline (Grafana needs one)
                {"color": color, "value": float(sig.threshold.value)},   # the declared threshold line
            ]
            if sig.threshold.unit:
                panel["unit"] = sig.threshold.unit
        panels.append(panel)

    output_path = f"dashboards/{project_id}-domain-dashboard.yaml"
    if not panels:
        return ArtifactResult(
            artifact_type="dashboard_spec",
            service_id=project_id,
            output_path=output_path,
            status="skipped",
            error_message="no signals to chart",
        )

    dashboard = {
        "title": f"{project_id} — domain observability",
        "uid": f"obs-domain-{project_id}",
        "panels": panels,
        "variables": [
            {"type": "prometheusDatasource", "name": "datasource", "label": "Datasource"}
        ],
    }
    header = (
        "# Generated by startd8 observability artifact generator (domain dashboard, E1)\n"
        f"# Source: {_SOURCE} — {len(panels)} panel(s)\n\n"
    )
    body = yaml.dump(dashboard, default_flow_style=False, sort_keys=False)
    return ArtifactResult(
        artifact_type="dashboard_spec",
        service_id=project_id,
        output_path=output_path,
        status="generated",
        content=header + body,
        derivations=[
            DerivationTrace(
                field="domain_dashboard_panels",
                source=_SOURCE,
                transformation=f"{len(panels)} signal(s) → dashboard panel(s)",
                tier="manifest",
            )
        ],
    )
