"""Shared GENERATED-header builders for backend_codegen artifacts.

One source of truth for the ``# GENERATED from … / # startd8-artifact: … / # schema-sha256: …``
provenance block, so the spine/derived renderers and the AI-layer renderers emit byte-identical
headers (previously the block was copy-pasted in ``crud_generator`` and ``derived``).

- :func:`header_standard` — spine/derived artifacts: one source contract (the Prisma schema), one hash.
- :func:`header_ai_layer` — AI-layer artifacts: THREE inputs (schema + ai_passes + human_inputs),
  so three hashes; drift is stale if *any* of them changes (FR-MA-5).
"""

from __future__ import annotations


def header_standard(source_file: str, sha: str, kind: str) -> str:
    """The spine/derived provenance header (source of truth: the Prisma schema)."""
    return (
        f"# GENERATED from {source_file} — do not edit by hand; "
        f"regenerate via `startd8 generate backend`.\n"
        f"# startd8-artifact: {kind}\n"
        f"# Source of truth: the Prisma schema.\n"
        f"# schema-sha256: {sha}"
    )


def header_emitted_contract(source_file: str, sha: str) -> str:
    """Provenance header for an EMITTED ``schema.prisma`` (OQ-PE-4 / FR-EMIT-5).

    Unlike :func:`header_standard`, the emitted contract's *source is the requirements doc*, not the
    schema itself, and it is regenerated via ``startd8 generate contract`` — not ``generate backend``
    (which *consumes* the schema). The generic header would be self-referential here ("source of
    truth: the Prisma schema" on the Prisma schema). The ``startd8-artifact: prisma-schema`` +
    ``schema-sha256:`` lines are preserved verbatim so "derived vs hand-authored" stays decidable.
    """
    return (
        f"# GENERATED from {source_file} — do not edit by hand; regenerate via\n"
        f"#   `startd8 generate contract --requirements {source_file} --promote`.\n"
        f"# startd8-artifact: prisma-schema\n"
        f"# Source of truth: the requirements doc (this schema is derived from prose).\n"
        f"# schema-sha256: {sha}"
    )


def header_imports(
    source_file: str,
    schema_sha: str,
    imports_sha: str,
    kind: str,
) -> str:
    """Import owned-kind provenance header — derives from two inputs (schema + imports.yaml), two
    hashes (FR-IMP-1 / R2-S5).

    Drift on ``app/import.py`` is **stale if either** the schema or ``imports.yaml`` changes (see
    :func:`startd8.backend_codegen.drift.imports_stale_reason`). The hash covers the whole
    ``imports.yaml`` text (the forms/pages precedent of hashing the whole manifest), so any import
    declaration edit conservatively re-stamps the importer — a cheap regenerate, never a miss.
    """
    return (
        f"# GENERATED from {source_file} (+ imports.yaml) — do not edit by hand; "
        f"regenerate via `startd8 generate backend`.\n"
        f"# startd8-artifact: {kind}\n"
        f"# Source of truth: the Prisma schema and the imports manifest.\n"
        f"# schema-sha256: {schema_sha}\n"
        f"# imports-sha256: {imports_sha}"
    )


def header_settings(source_file: str, sha: str, mode: str) -> str:
    """Settings provenance header — **self-describes the baked deployment mode** (FR-CFG-7a).

    ``app/settings.py`` is the single file whose generated bytes vary by deployment mode. The mode is
    embedded here (``# startd8-mode: …``) so the schema-only prime-contractor skip-hook
    (:func:`startd8.backend_codegen.drift.owned_file_in_sync`, which passes only ``schema_text``) can
    re-render it from the file's OWN header — **with no** ``app.yaml`` **read** — exactly as the AI
    service self-embeds ``ai-agent-spec``. A schema change is still caught by ``schema-sha256``; a
    hand-edit of the mode line is caught by the full byte re-render in
    :func:`startd8.backend_codegen.drift.check_drift`.
    """
    return (
        f"# GENERATED from {source_file} — do not edit by hand; "
        f"regenerate via `startd8 generate backend`.\n"
        f"# startd8-artifact: python-settings\n"
        f"# startd8-mode: {mode}\n"
        f"# Source of truth: the Prisma schema and the declared deployment mode.\n"
        f"# schema-sha256: {sha}"
    )


def header_pages(
    source_file: str,
    schema_sha: str,
    pages_sha: str,
    kind: str,
) -> str:
    """Content-pages provenance header — derives from two inputs (schema + pages.yaml), two hashes.

    Drift on a content-page artifact is **stale if either** the schema or ``pages.yaml`` changes (see
    :func:`startd8.backend_codegen.drift.pages_stale_reason`). The page *prose* (``app/pages/*.md``)
    is deliberately **not** an input here — it lives only in the untracked rendered body fragment, so
    editing prose never flags drift (mirrors the ai-passes prompt rule).
    """
    return (
        f"# GENERATED from {source_file} (+ pages.yaml) — do not edit by hand; "
        f"regenerate via `startd8 generate backend`.\n"
        f"# startd8-artifact: {kind}\n"
        f"# Source of truth: the Prisma schema and the pages manifest.\n"
        f"# schema-sha256: {schema_sha}\n"
        f"# pages-sha256: {pages_sha}"
    )


def header_pages_tmpl(
    source_file: str,
    schema_sha: str,
    pages_sha: str,
    kind: str,
    entity: str = "",
) -> str:
    """:func:`header_pages` wrapped in a Jinja ``{# … #}`` comment for ``.html`` page templates.

    Same two-hash provenance as :func:`header_pages`, but invisible at render time. ``entity`` carries
    the page slug-name in the ``startd8-entity`` slot so drift re-renders the right page template.
    """
    lines = [
        "{#",
        f"# GENERATED from {source_file} (+ pages.yaml) — do not edit by hand; "
        f"regenerate via `startd8 generate backend`.",
        f"# startd8-artifact: {kind}",
    ]
    if entity:
        lines.append(f"# startd8-entity: {entity}")
    lines.append("# Source of truth: the Prisma schema and the pages manifest.")
    lines.append(f"# schema-sha256: {schema_sha}")
    lines.append(f"# pages-sha256: {pages_sha}")
    lines.append("#}")
    return "\n".join(lines)


def header_forms(
    source_file: str,
    schema_sha: str,
    forms_sha: str,
    kind: str,
    entity: str = "",
) -> str:
    """Form-behavior provenance header — derives from two inputs (schema + views.yaml), two hashes.

    Drift on a forms-configured artifact is **stale if either** the schema or ``views.yaml``
    changes (see :func:`startd8.backend_codegen.drift.forms_stale_reason`). The hash covers the
    whole ``views.yaml`` text (matching the pages precedent of hashing the whole manifest), so a
    composite-view edit conservatively re-stamps the web routes — a cheap regenerate, never a miss.

    ``entity`` (optional) carries a name in the ``startd8-entity`` slot so a per-name artifact (e.g. a
    per-flow router ``app/flows/<name>.py`` or a per-editor router) can be re-rendered by-name in drift.
    Omitted → no entity line, byte-identical to the app-wide form (``fastapi-web-forms`` is unaffected).
    """
    lines = [
        f"# GENERATED from {source_file} (+ views.yaml) — do not edit by hand; "
        f"regenerate via `startd8 generate backend`.",
        f"# startd8-artifact: {kind}",
    ]
    if entity:
        lines.append(f"# startd8-entity: {entity}")
    lines.append("# Source of truth: the Prisma schema and the forms manifest.")
    lines.append(f"# schema-sha256: {schema_sha}")
    lines.append(f"# forms-sha256: {forms_sha}")
    return "\n".join(lines)


def header_forms_tmpl(
    source_file: str,
    schema_sha: str,
    forms_sha: str,
    kind: str,
    entity: str = "",
) -> str:
    """:func:`header_forms` wrapped in a Jinja ``{# … #}`` comment for ``.html`` templates.

    Same two-hash provenance as :func:`header_forms`, but invisible at render time. ``entity``
    carries the entity name in the ``startd8-entity`` slot so drift re-renders the right template.
    """
    lines = [
        "{#",
        f"# GENERATED from {source_file} (+ views.yaml) — do not edit by hand; "
        f"regenerate via `startd8 generate backend`.",
        f"# startd8-artifact: {kind}",
    ]
    if entity:
        lines.append(f"# startd8-entity: {entity}")
    lines.append("# Source of truth: the Prisma schema and the forms manifest.")
    lines.append(f"# schema-sha256: {schema_sha}")
    lines.append(f"# forms-sha256: {forms_sha}")
    lines.append("#}")
    return "\n".join(lines)


def header_ai_layer(
    source_file: str,
    schema_sha: str,
    passes_sha: str,
    human_sha: str,
    kind: str,
) -> str:
    """AI-layer provenance header — derives from three inputs, so it carries three hashes.

    Drift on an AI-layer file is **stale if any one of** schema / ai_passes / human_inputs changes
    (see :func:`startd8.backend_codegen.drift.ai_layer_stale_reason`).
    """
    return (
        f"# GENERATED from {source_file} (+ ai_passes.yaml + human_inputs.yaml) — do not edit by "
        f"hand; regenerate via `startd8 generate backend`.\n"
        f"# startd8-artifact: {kind}\n"
        f"# Source of truth: the Prisma schema, AI passes, and human inputs.\n"
        f"# schema-sha256: {schema_sha}\n"
        f"# passes-sha256: {passes_sha}\n"
        f"# human-inputs-sha256: {human_sha}"
    )
