# Copyright 2026 StartD8 Contributors
# SPDX-License-Identifier: LicenseRef-Equitable-Use-1.0

"""role-rubric parity gate (R2-S5, N3).

Before the benchmarking one-off ``reviewer_roles_to_roster.py`` is redirected to the SDK, this asserts
the SDK ``role-rubric`` adapter reproduces the one-off's output on the *real* ``reviewer_roles.yaml``.
The golden was generated by running the original one-off converter (see ``fixtures/``); if the
adapter's mapping ever drifts from it, this test fails.
"""

from __future__ import annotations

from pathlib import Path

import yaml

from startd8.stakeholder_panel.adapters.role_rubric import RoleRubricAdapter
from startd8.stakeholder_panel.roster import parse_roster, validate_roster

_FIXTURES = Path(__file__).resolve().parent / "fixtures"


def _load(name):
    return (_FIXTURES / name).read_text(encoding="utf-8")


def test_adapter_output_matches_the_oneoff_converter():
    adapted = RoleRubricAdapter().adapt(_load("reviewer_roles.yaml")).roster.to_dict()
    golden = yaml.safe_load(_load("reviewer_roles_oneoff_roster.yaml"))
    # Semantic parity: identical personas (dict compare ignores key order). protocol_version differs
    # (the SDK stamps it; the one-off did not), so we compare the personas payload.
    assert adapted["personas"] == golden["personas"]
    assert len(adapted["personas"]) == 5


def test_adapter_output_ingests_cleanly():
    roster = RoleRubricAdapter().adapt(_load("reviewer_roles.yaml")).roster
    reparsed = parse_roster(yaml.safe_dump(roster.to_dict()))
    assert validate_roster(reparsed) == []
    assert [p.role_id for p in reparsed.personas] == [
        "se-manager",
        "sre",
        "frontend",
        "backend",
        "security",
    ]
