"""TUI-agnostic installer for embedding the cap-dev-pipe pipeline into a project.

This module implements the install/configure/verify logic behind the TUI flow
described in ``docs/design/TUI_CAPDEVPIPE_INSTALL_{REQUIREMENTS,PLAN}.md``. It is
deliberately **TUI-agnostic** (NFR-7): it imports no ``questionary``/``rich`` and is
driven entirely from an :class:`InstallConfig` dict, so the future workflow registry —
and the test suite — can run a full install with no TUI present. The TUI handler is a
thin caller that gathers an :class:`InstallConfig` and invokes :meth:`execute`.

Two embedding methods (FR-4): **symlink** (single source of truth with the canonical
checkout) and **copy** (shells out to the canonical ``install-cap-dev-pipe.sh`` rsync
installer, then reconciles). Both derive their action list from the canonical shared
planner ``resolve_install_plan`` (FR-A7) — the SDK owns the pipeline.env merge, wrapper,
language profiles, gitignore and transactional rollback layered on top, but no longer
re-derives which inventory entries are symlinked vs copied.

Failures raise the SDK exception hierarchy from :mod:`startd8.exceptions` (never bare
``OSError``/``ValueError``) so messages structurally name the offending path and a
remediation (NFR-5). Every planned action and subprocess invocation is logged via the
SDK logger for durable diagnosability (NFR-8).
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence

from .capdevpipe_embed_manifest import (
    DEFAULT_EMBED_PROFILE,
    check_embed_namespace,
    resolve_embed_inventory,
    resolve_embed_plan,
)
from .config import get_config_manager
from .exceptions import ConfigurationError, FileOperationError, ValidationError
from .logging_config import get_logger

logger = get_logger(__name__)

# --------------------------------------------------------------------------- #
# Constants
# --------------------------------------------------------------------------- #

#: Default location of the canonical cap-dev-pipe checkout (FR-2).
DEFAULT_SOURCE = Path.home() / "Documents" / "dev" / "cap-dev-pipe"

#: Directory created inside the target project to hold the embedded pipeline.
EMBED_DIR_NAME = ".cap-dev-pipe"

#: Persisted install manifest, the authoritative inventory (FR-18).
MANIFEST_FILENAME = ".install-manifest.json"

#: Manifest schema version. The field is written from v1; forward-compatible *reading*
#: (graceful fallback on an unknown version) is added in P2 (R3-S5 / task #11).
MANIFEST_VERSION = 1

#: Timeouts (seconds) for installer subprocesses (NFR-8 reliability): a hung external
#: script must not block the TUI / headless run indefinitely. ``TimeoutExpired`` is a
#: ``subprocess.SubprocessError`` and so surfaces as :class:`FileOperationError` via
#: :meth:`CapDevPipeInstaller._run_subprocess`.
SUBPROCESS_TIMEOUT_INSTALL = 600.0  # rsync copy installer (install-cap-dev-pipe.sh)
SUBPROCESS_TIMEOUT_VERIFY = 120.0  # run.sh --list-langs

#: The four ``pipeline.env`` keys the installer owns. Any other key found in an existing
#: ``pipeline.env`` is preserved across reconcile / replace-env / upgrade (FR-7, R3-F5).
MANAGED_ENV_KEYS = ("CONTEXTCORE_ROOT", "SDK_ROOT", "PROJECT_ROOT", "PROJECT_NAME")

#: Files that mark a directory as a genuine cap-dev-pipe checkout (FR-2 validation).
#: The embed inventory itself comes from ``embed-manifest.yaml`` (Increment A6 / FR-16).
SOURCE_MARKERS = (
    "embed-manifest.yaml",
    "install-cap-dev-pipe.sh",
    "run.sh",
    "design",
    "prompts",
)

#: Wrapper template in the source checkout; placeholders are substituted (FR-8).
WRAPPER_TEMPLATE_NAME = "project-cap-dlv-pipe.sh.template"

#: Header for a freshly written pipeline.env (NFR-4: no secrets).
PIPELINE_ENV_HEADER = (
    "# Generated by the startd8 cap-dev-pipe installer — adjust paths as needed.\n"
    "# Do not commit secrets here.\n"
)

#: ConfigManager preference keys for remembered installer settings (FR-15).
PREF_SOURCE_PATH = "capdevpipe.source_path"
PREF_INSTALL_METHOD = "capdevpipe.install_method"
PREF_CONTEXTCORE_ROOT = "capdevpipe.CONTEXTCORE_ROOT"
PREF_SDK_ROOT = "capdevpipe.SDK_ROOT"

#: Matches the ``ln -s $CAP_DEV_PIPE/<name>`` lines in cap-dev-pipe's CLAUDE.md embed block.
_LN_S_EMBED_RE = re.compile(r"^\s*ln -s\s+\$CAP_DEV_PIPE/(\S+)\s*$", re.MULTILINE)


def parse_canonical_embed_scripts(claude_md_text: str) -> List[str]:
    """Extract the canonical embedded-script list from cap-dev-pipe's CLAUDE.md (FR-5 / D-10).

    The single source of truth for the embed set is the ``ln -s $CAP_DEV_PIPE/<name>`` block
    under "Embedding in a Project". Returns the script names in document order. The profile
    example's ``ln -sf "../../PLAN.md"`` lines do not reference ``$CAP_DEV_PIPE`` and so are
    not matched. Underscore aliases are intentionally absent from this block — they are a
    separate correctness addition (imported as modules). Legacy helper retained for tests
    that parse CLAUDE.md directly; the installer consumes ``embed-manifest.yaml`` instead.
    """
    return _LN_S_EMBED_RE.findall(claude_md_text)


# --------------------------------------------------------------------------- #
# Enums
# --------------------------------------------------------------------------- #


class InstallMethod(str, Enum):
    """How the pipeline scripts / profile docs are embedded (FR-4)."""

    SYMLINK = "symlink"
    COPY = "copy"


class ReRunMode(str, Enum):
    """Idempotent re-run modes for an existing install (FR-12)."""

    RECONFIGURE = "reconfigure"  # re-prompt + rewrite config; leave embedded scripts
    UPGRADE = "upgrade"  # refresh script symlinks / re-rsync; prune orphans; keep config+profiles
    REPAIR = "repair"  # recreate only missing/broken symlinks, then verify
    REPLACE_PIPELINE_ENV = (
        "replace-pipeline.env"  # rewrite managed keys; preserve non-managed
    )
    DOCTOR = "doctor"  # source-relocation / health check (FR-17; P2)


class ActionType(str, Enum):
    """The kind of write a planned :class:`Action` performs."""

    MKDIR = "mkdir"
    SYMLINK = "symlink"
    COPY_FILE = "copy_file"
    COPY_TREE = "copy_tree"
    WRITE_FILE = "write_file"
    CHMOD = "chmod"
    GITIGNORE_ENSURE = "gitignore_ensure"
    RUN_SUBPROCESS = "run_subprocess"
    #: Apply-time copy-path reconcile (FR-6): merge the four managed pipeline.env keys into
    #: the rsync-written file and remove the auto-linked root java profile. Modeled as a
    #: single action because its effect depends on the rsync *output* (unknown at plan time).
    RECONCILE_COPY = "reconcile_copy"


class ManifestState(str, Enum):
    """In-progress marker carried by the manifest (FR-18; crash semantics in P2)."""

    PENDING = "pending"
    COMPLETE = "complete"


# --------------------------------------------------------------------------- #
# Data types
# --------------------------------------------------------------------------- #


@dataclass
class ProfileSpec:
    """A language profile to create (FR-9): ``<lang>/`` wired to plan/requirements docs."""

    lang: str
    plan: Optional[Path] = None
    reqs: Optional[Path] = None


@dataclass
class InstallConfig:
    """Fully-resolved install inputs — the headless drive surface (NFR-7).

    The TUI handler builds this from prompts; tests construct it directly. All decisions
    are pre-made here so :meth:`CapDevPipeInstaller.execute` needs no interactive callback.
    """

    source_path: Path
    target_root: Path
    method: InstallMethod
    #: The four managed keys (FR-7). May be partial; ``execute`` blocks rather than writing
    #: a blank for any undetectable key (R2-S6 / R2-F2).
    pipeline_env: Dict[str, str] = field(default_factory=dict)
    default_lang: str = "python"
    profiles: List[ProfileSpec] = field(default_factory=list)
    #: Profile-doc embedding method; defaults to ``method`` (and is forced to COPY on
    #: Windows). ``None`` means "derive at execute time".
    profile_method: Optional[InstallMethod] = None
    #: Re-run mode when an install already exists (FR-12); ``None`` for a fresh install.
    rerun_mode: Optional[ReRunMode] = None
    #: Explicit opt-in to execute the copy installer from a non-default source (R3-S1/#13).
    #: The TUI sets this after surfacing/confirming the script path; a default-location source
    #: is trusted without it.
    trust_source: bool = False
    #: Embed profile passed to ``embed-manifest.yaml`` resolution (FR-16). Default ``full``.
    embed_profile: str = DEFAULT_EMBED_PROFILE


@dataclass
class Action:
    """One idempotent, replayable planned write (FR-13 preview == FR-16 execute set).

    Per R2-S3 every action is *create-or-skip-if-correct*: :meth:`is_satisfied` reports
    whether the on-disk state already matches, so ``repair``/``upgrade`` can replay the
    list filtered to missing/incorrect entries.
    """

    type: ActionType
    target: Path
    source: Optional[Path] = None
    content: Optional[str] = None
    mode: Optional[int] = None
    detail: Optional[str] = None
    argv: Optional[Sequence[str]] = None
    #: Working directory for a RUN_SUBPROCESS action (defaults to ``target`` if unset).
    cwd: Optional[Path] = None

    def describe(self) -> str:
        """Human-readable one-line description for the preview panel and logs."""
        if self.type is ActionType.SYMLINK:
            return f"symlink {self.target} -> {self.source}"
        if self.type in (ActionType.COPY_FILE, ActionType.COPY_TREE):
            return f"copy {self.source} -> {self.target}"
        if self.type is ActionType.WRITE_FILE:
            mode = f" (mode {oct(self.mode)})" if self.mode is not None else ""
            return f"write {self.target}{mode}"
        if self.type is ActionType.RUN_SUBPROCESS:
            return f"run {' '.join(self.argv or [])}"
        if self.type is ActionType.MKDIR:
            return f"mkdir {self.target}"
        if self.type is ActionType.CHMOD:
            return f"chmod {oct(self.mode) if self.mode is not None else '?'} {self.target}"
        if self.type is ActionType.GITIGNORE_ENSURE:
            return f"gitignore ensure {self.detail} in {self.target}"
        return f"{self.type.value} {self.target}"

    def is_satisfied(self) -> bool:
        """Whether on-disk state already matches this action (idempotency, R2-S3).

        ``True`` means :meth:`CapDevPipeInstaller.execute` skips the action on replay, so
        ``repair``/``upgrade`` re-run the list touching only missing/incorrect entries.
        ``RUN_SUBPROCESS`` is never "satisfied" (the external installer is itself idempotent,
        so re-running is safe and cheap).
        """
        t = self.target
        if self.type is ActionType.MKDIR:
            return t.is_dir()
        if self.type is ActionType.SYMLINK:
            # Satisfied iff it is a symlink already pointing at the intended (absolute) source.
            return t.is_symlink() and os.readlink(t) == str(self.source)
        if self.type is ActionType.WRITE_FILE:
            if not t.is_file() or t.is_symlink():
                return False
            if (
                self.content is not None
                and t.read_text(encoding="utf-8") != self.content
            ):
                return False
            if self.mode is not None and (t.stat().st_mode & 0o777) != self.mode:
                return False
            return True
        if self.type is ActionType.COPY_FILE:
            return t.is_file()
        if self.type is ActionType.COPY_TREE:
            return t.is_dir()
        if self.type is ActionType.CHMOD:
            return t.exists() and (t.stat().st_mode & 0o777) == (self.mode or 0)
        if self.type is ActionType.GITIGNORE_ENSURE:
            if not t.is_file() or self.detail is None:
                return False
            lines = t.read_text(encoding="utf-8").splitlines()
            return self.detail in lines
        # RUN_SUBPROCESS (and any unhandled type) is never pre-satisfied — always runs.
        return False


@dataclass
class Manifest:
    """Authoritative inventory persisted to ``.cap-dev-pipe/.install-manifest.json`` (FR-18)."""

    method: InstallMethod
    source_path: Path
    #: The full set of installer-*managed* paths (every owned-type planned target), NOT
    #: only paths this particular run physically created — a re-run/upgrade/repair records
    #: pre-existing and already-satisfied targets here too. This is the right inventory for
    #: repair/drift (the current consumers), which need the complete expected set. Run-scoped
    #: rollback uses a separate list (``_run_actions.newly_created``). NOTE for the P2
    #: uninstall (#?): do NOT blind-``rm`` this list — it includes ``pipeline.env`` (which may
    #: hold user-added non-managed keys) and any pre-existing content. Uninstall must diff
    #: against what it can prove it created, or confirm per path.
    created_paths: List[Path] = field(default_factory=list)
    profiles: List[str] = field(default_factory=list)
    state: ManifestState = ManifestState.COMPLETE
    manifest_version: int = MANIFEST_VERSION
    #: Embed profile and the canonical top-level managed-path set (FR-A6). These make the
    #: manifest readable by canonical ``verify_embed``/``repair_embed`` — which require
    #: ``embed_profile``/``install_method``/``managed_paths`` and otherwise crash with a raw
    #: ``KeyError`` on an SDK-written manifest (interop bug C1, spike-validated).
    embed_profile: str = DEFAULT_EMBED_PROFILE
    managed_paths: List[str] = field(default_factory=list)
    #: UTC ISO-8601 install timestamp (canonical field). ``None`` → stamped at ``to_dict`` time.
    installed_at: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Serialize for ``.install-manifest.json`` (FR-18 / FR-A6).

        Emits the **canonical** field set (so ``pipeline verify``/``repair`` accept the file)
        plus SDK-only bookkeeping (``created_paths``/``profiles``) that canonical
        ``read_install_manifest`` ignores as unknown keys. ``schema_version`` and
        ``manifest_version`` are both written at the same value for either reader.
        """
        return {
            "schema_version": self.manifest_version,
            "manifest_version": self.manifest_version,
            "install_method": self.method.value,
            "source_path": str(self.source_path),
            "embed_profile": self.embed_profile,
            "installed_at": self.installed_at
            or datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "managed_paths": sorted(set(self.managed_paths)),
            "state": self.state.value,
            # SDK-only bookkeeping (rollback / orphan-prune / uninstall). Canonical ignores these.
            "created_paths": [str(p) for p in self.created_paths],
            "profiles": list(self.profiles),
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Manifest":
        """Reconstruct from parsed JSON (FR-18), tolerating legacy and canonical shapes (FR-A10).

        Reads ``install_method`` (canonical) falling back to legacy ``method``; ``schema_version``
        falling back to legacy ``manifest_version``. A pre-A6 SDK manifest (``method`` +
        ``created_paths``, no ``managed_paths``/``embed_profile``) still loads; the next write
        upgrades it to the canonical superset in place (migration-on-write, OQ-3).
        """
        method_raw = data.get("install_method", data.get("method"))
        return cls(
            method=InstallMethod(method_raw),
            source_path=Path(data["source_path"]),
            created_paths=[Path(p) for p in data.get("created_paths", [])],
            profiles=list(data.get("profiles", [])),
            state=ManifestState(data.get("state", ManifestState.COMPLETE.value)),
            manifest_version=int(
                data.get("schema_version", data.get("manifest_version", MANIFEST_VERSION))
            ),
            embed_profile=str(data.get("embed_profile", DEFAULT_EMBED_PROFILE)),
            managed_paths=list(data.get("managed_paths", [])),
            installed_at=data.get("installed_at"),
        )


@dataclass
class DocCandidates:
    """Detected plan/requirements docs for profile wiring (FR-9)."""

    plans: List[Path] = field(default_factory=list)
    reqs: List[Path] = field(default_factory=list)


@dataclass
class ExecuteResult:
    """Outcome of :meth:`CapDevPipeInstaller.execute` (FR-16)."""

    success: bool
    actions_applied: List[Action] = field(default_factory=list)
    manifest_path: Optional[Path] = None
    rolled_back: bool = False
    repairable: bool = False
    error: Optional[str] = None


@dataclass
class VerifyResult:
    """Outcome of :meth:`CapDevPipeInstaller.verify` (FR-11)."""

    passed: bool
    listed_langs: List[str] = field(default_factory=list)
    expected_langs: List[str] = field(default_factory=list)
    single_source_ok: bool = False
    exit_code: Optional[int] = None
    stderr: str = ""
    #: Set when a symlink install's canonical source has moved/been deleted (FR-17; P2).
    dangling_source: Optional[Path] = None
    message: str = ""


@dataclass
class InstallState:
    """What :meth:`CapDevPipeInstaller.detect_existing` found at the target (FR-12)."""

    exists: bool
    manifest: Optional[Manifest] = None
    #: True when a prior run left a ``pending`` manifest (crash recovery; P2 / R2-S7).
    pending: bool = False
    broken_symlinks: List[Path] = field(default_factory=list)
    dangling_source: Optional[Path] = None


# --------------------------------------------------------------------------- #
# Installer
# --------------------------------------------------------------------------- #


class CapDevPipeInstaller:
    """Installs and configures cap-dev-pipe into a target project (TUI-agnostic).

    Construct with no arguments and drive via :meth:`execute` / :meth:`verify` /
    :meth:`apply_mode`, passing an :class:`InstallConfig`. All file/shell work happens
    here; the TUI handler only gathers inputs and renders results.
    """

    def __init__(self) -> None:
        self.logger = logger

    # -- platform ---------------------------------------------------------- #

    @staticmethod
    def _symlinks_available() -> bool:
        """Whether symlinks are usable on this platform (FR-4 / D-9).

        On Windows, symlinks need admin/dev-mode, so the flow defaults to / forces copy
        for both scripts and profile docs. Patchable in tests to exercise the fallback.
        """
        return os.name != "nt"

    def _resolve_profile_method(self, cfg: InstallConfig) -> InstallMethod:
        """The method used for profile docs: explicit override, else cfg.method, forced
        to COPY when symlinks are unavailable (FR-9 / D-9)."""
        chosen = cfg.profile_method or cfg.method
        if chosen is InstallMethod.SYMLINK and not self._symlinks_available():
            return InstallMethod.COPY
        return chosen

    # -- diagnosability (NFR-8) -------------------------------------------- #

    def _log_action(self, action: Action) -> None:
        """Log a planned/applied action for a durable trail (NFR-8)."""
        self.logger.info(
            "capdevpipe action: %s",
            action.describe(),
            extra={
                "pipeline_name": "capdevpipe_install",
                "action_type": action.type.value,
            },
        )

    def _run_subprocess(
        self,
        argv: Sequence[str],
        cwd: Optional[Path] = None,
        timeout: Optional[float] = None,
    ) -> subprocess.CompletedProcess:
        """Run a subprocess, logging the invocation and captured output (NFR-8).

        Used for the copy installer (FR-6) and verification (FR-11). Output is captured
        (text) and logged so a field failure leaves a trail beyond the on-screen message.
        Raises :class:`FileOperationError` if the executable cannot be launched.
        """
        argv = [str(a) for a in argv]
        self.logger.info(
            "capdevpipe subprocess: %s (cwd=%s)",
            " ".join(argv),
            cwd,
            extra={"pipeline_name": "capdevpipe_install"},
        )
        try:
            proc = subprocess.run(
                argv,
                cwd=str(cwd) if cwd else None,
                capture_output=True,
                text=True,
                timeout=timeout,
            )
        except (OSError, subprocess.SubprocessError) as exc:
            raise FileOperationError(
                f"Failed to run {argv[0]!r}: {exc}. Check the file exists and is executable.",
                file_path=argv[0],
                original_error=exc,
            ) from exc
        self.logger.info(
            "capdevpipe subprocess exit=%s stdout=%d bytes stderr=%d bytes",
            proc.returncode,
            len(proc.stdout or ""),
            len(proc.stderr or ""),
            extra={"pipeline_name": "capdevpipe_install"},
        )
        if proc.stderr:
            self.logger.debug("capdevpipe subprocess stderr: %s", proc.stderr.strip())
        return proc

    # -- source / target (FR-2, FR-3) -------------------------------------- #

    def locate_source(self, override: Optional[Path] = None) -> Path:
        """Locate and validate the canonical cap-dev-pipe checkout (FR-2).

        Defaults to :data:`DEFAULT_SOURCE`; ``override`` takes precedence. Validates the
        directory has the :data:`SOURCE_MARKERS`. Raises :class:`ConfigurationError` with
        the path and a remediation if it is missing or not a real checkout.
        """
        source = (Path(override) if override else DEFAULT_SOURCE).expanduser()
        if not source.is_dir():
            raise ConfigurationError(
                f"cap-dev-pipe source not found at {source}. Point to a valid cap-dev-pipe "
                f"checkout (clone it or pass the correct source path)."
            )
        missing = [m for m in SOURCE_MARKERS if not (source / m).exists()]
        if missing:
            raise ConfigurationError(
                f"{source} is not a valid cap-dev-pipe checkout (missing: "
                f"{', '.join(missing)}). Point to the cap-dev-pipe repository root."
            )
        if not (source / "pipeline" / "embed_manifest.py").is_file():
            raise ConfigurationError(
                f"{source} is missing pipeline/embed_manifest.py. Point to a cap-dev-pipe "
                f"checkout with modular embed support (Increment A+)."
            )
        return source.resolve()

    def _validate_target(self, cfg: InstallConfig) -> None:
        """Validate the target project root (FR-3): a directory, never the source tree."""
        target_path = Path(cfg.target_root)
        if not target_path.is_dir():
            raise ValidationError(
                f"Target project root is not a directory: {cfg.target_root}. "
                f"Choose an existing project directory.",
                field="target_root",
                value=str(cfg.target_root),
            )
        target = Path(os.path.realpath(target_path))
        source = Path(os.path.realpath(cfg.source_path))
        if target == source or source in target.parents:
            raise ValidationError(
                f"Refusing to install into the cap-dev-pipe source tree ({target}). "
                f"Choose a separate target project directory.",
                field="target_root",
                value=str(target),
            )

    # -- planning / execution (FR-13, FR-16) ------------------------------- #

    def _effective_method(self, cfg: InstallConfig) -> InstallMethod:
        """The method actually used: forced to COPY when symlinks are unavailable (FR-4 / D-9).

        On Windows (no reliable symlinks) a requested ``symlink`` install falls back to
        ``copy`` for **scripts** as well as profile docs — the installer enforces this so a
        caller cannot accidentally request an unsupportable symlink install.
        """
        if cfg.method is InstallMethod.SYMLINK and not self._symlinks_available():
            return InstallMethod.COPY
        return cfg.method

    def plan_actions(self, cfg: InstallConfig) -> List[Action]:
        """Compute the ordered, idempotent action list (FR-13 preview / FR-16 source).

        This is the *single* source of writes for :meth:`execute`, :meth:`verify`, and
        rollback — the same list the TUI previews is the list ``execute`` consumes
        (R2-F4). Each action is replayable (R2-S3). Composed from the per-concern builders
        (tasks #4–#7).
        """
        self._validate_target(cfg)
        # Namespace guard (FR-A8): refuse to embed a `pipeline` package into a project that
        # already has a generic `pipeline` module which would shadow it. Delegated to canonical.
        check_embed_namespace(Path(cfg.source_path), cfg.embed_profile, cfg.target_root)
        actions: List[Action] = []
        if self._effective_method(cfg) is InstallMethod.SYMLINK:
            actions += self.embed_symlink(cfg)
            actions += self.write_pipeline_env(cfg)
        else:
            # Copy path: rsync writes scripts/design/prompts/pipeline.env; reconcile fixes
            # the four managed keys + the auto-linked root java profile (FR-6).
            actions += self.embed_copy(cfg)
            actions += self.reconcile_copy_install(cfg)
        actions += self.generate_wrapper(cfg)
        for profile in cfg.profiles:
            actions += self.create_profile(cfg, profile)
        actions += self.update_gitignore(cfg)
        return actions

    def execute(
        self, cfg: InstallConfig, actions: Optional[List[Action]] = None
    ) -> ExecuteResult:
        """Run the planned actions in order, confined to ``target_root`` (FR-16, NFR-6).

        Applies each action idempotently (skipping those already satisfied) and writes the
        install manifest on success. On failure: the symlink path rolls back its own writes;
        a path containing an external subprocess (copy/rsync) cannot be cleanly reversed, so
        it returns a repairable state instead (R2-S2).

        **Preview fidelity (FR-13 / FR-16 — R4-F5).** Pass the *already-computed* preview list
        as ``actions`` so the list the TUI showed is the exact list executed — the "single
        planned action list" the requirement mandates. When ``actions`` is ``None`` the plan is
        computed here (headless/library callers that skip the preview). Either way the set is
        deterministic, but consuming the preview removes the recompute-and-hope gap.

        Refuses to layer onto a prior **pending** (crashed/incomplete) install (R2-S7): the
        caller should run ``apply_mode(... REPAIR)`` instead. TOCTOU symlink confinement
        (R2-S5) and the pending/complete crash marker are enforced here and in
        :meth:`_run_actions`.
        """
        if self.detect_existing(cfg.target_root).pending:
            return ExecuteResult(
                success=False,
                repairable=True,
                error=(
                    "A prior run left an incomplete (pending) install. Re-run and choose "
                    "'repair' to complete it safely rather than layering a second install."
                ),
            )
        if actions is None:
            actions = self.plan_actions(cfg)
        return self._run_actions(actions, cfg)

    # -- execution engine (private) ---------------------------------------- #

    def _assert_embed_not_escaping(self, cfg: InstallConfig) -> None:
        """Refuse if ``.cap-dev-pipe/`` is a pre-existing symlink escaping the target (R2-S5).

        A planted/accidental ``target/.cap-dev-pipe -> /elsewhere`` would otherwise redirect
        every write outside the target. Per-action confinement also catches this mid-run; this
        pre-flight refuses upfront with a clear message.
        """
        embed = Path(cfg.target_root) / EMBED_DIR_NAME
        if embed.is_symlink():
            resolved = Path(os.path.realpath(embed))
            root = Path(os.path.realpath(cfg.target_root))
            if resolved != root and root not in resolved.parents:
                raise FileOperationError(
                    f"Refusing to install: {embed} is a pre-existing symlink to {resolved}, "
                    f"outside the target. Remove it and re-run.",
                    file_path=str(embed),
                )

    def _confine(self, path: Path, target_root: Path) -> None:
        """Refuse a write whose containing directory escapes ``target_root`` (NFR-6, basic).

        Resolves the **parent** directory (where the entry is created), not the entry itself:
        a script symlink legitimately points at an absolute source path *outside* the target
        (NFR-3), so following the leaf would false-positive. Resolving the parent still catches
        a pre-existing symlink *component* that redirects the write outside the target; P2
        (task #12) hardens the full TOCTOU story.
        """
        root = Path(os.path.realpath(target_root))
        parent = Path(os.path.realpath(path.parent))
        if parent != root and root not in parent.parents:
            raise FileOperationError(
                f"Refusing to write outside the target: {path} would be created under "
                f"{parent}, outside {root}. Choose a target inside the project directory.",
                file_path=str(path),
            )

    def _apply_action(self, action: Action, cfg: InstallConfig) -> None:
        """Perform one action's filesystem/subprocess effect. Raises on failure."""
        t = action.target
        if action.type is ActionType.MKDIR:
            t.mkdir(parents=True, exist_ok=True)
        elif action.type is ActionType.SYMLINK:
            if action.source is None:
                raise FileOperationError(
                    f"symlink action for {t} has no source", file_path=str(t)
                )
            t.parent.mkdir(parents=True, exist_ok=True)
            if t.is_symlink() or t.exists():
                t.unlink()
            os.symlink(action.source, t)
        elif action.type is ActionType.COPY_FILE:
            if action.source is None:
                raise FileOperationError(
                    f"copy action for {t} has no source", file_path=str(t)
                )
            t.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(action.source, t)
        elif action.type is ActionType.COPY_TREE:
            if action.source is None:
                raise FileOperationError(
                    f"copy-tree action for {t} has no source", file_path=str(t)
                )
            shutil.copytree(action.source, t, dirs_exist_ok=True)
        elif action.type is ActionType.WRITE_FILE:
            t.parent.mkdir(parents=True, exist_ok=True)
            t.write_text(action.content or "", encoding="utf-8")
            if action.mode is not None:
                os.chmod(t, action.mode)
        elif action.type is ActionType.CHMOD:
            if action.mode is not None:
                os.chmod(t, action.mode)
        elif action.type is ActionType.GITIGNORE_ENSURE:
            self._append_gitignore_line(t, action.detail or "")
        elif action.type is ActionType.RUN_SUBPROCESS:
            proc = self._run_subprocess(
                action.argv or [],
                cwd=action.cwd or t,
                timeout=SUBPROCESS_TIMEOUT_INSTALL,
            )
            if proc.returncode != 0:
                raise FileOperationError(
                    f"Command failed (exit {proc.returncode}): "
                    f"{' '.join(str(a) for a in action.argv or [])}. {proc.stderr.strip()}",
                    file_path=str(t),
                )
        elif action.type is ActionType.RECONCILE_COPY:
            self._reconcile_copy(cfg)
        else:  # pragma: no cover - defensive
            raise FileOperationError(
                f"Unknown action type {action.type!r}", file_path=str(t)
            )

    @staticmethod
    def _append_gitignore_line(gitignore: Path, line: str) -> None:
        """Append ``line`` to ``gitignore`` if absent, preserving a trailing newline (FR-10)."""
        existing = gitignore.read_text(encoding="utf-8") if gitignore.is_file() else ""
        if line in existing.splitlines():
            return
        prefix = "" if existing == "" or existing.endswith("\n") else "\n"
        gitignore.write_text(existing + prefix + line + "\n", encoding="utf-8")

    def _run_actions(self, actions: List[Action], cfg: InstallConfig) -> ExecuteResult:
        """Apply the planned action list with idempotent skip + rollback/repairable (FR-16).

        Writes a ``pending`` manifest first and a ``complete`` one last (R2-S7 crash marker):
        a process killed mid-run leaves ``pending`` so a later :meth:`execute` routes to repair.
        On a fresh-install failure the symlink path rolls back its own writes (including the
        pending manifest); the copy path is repairable-only (R2-S2), leaving ``pending``.
        """
        self._assert_embed_not_escaping(cfg)  # R2-S5 pre-flight
        effective = self._effective_method(cfg)
        embed = Path(cfg.target_root) / EMBED_DIR_NAME
        embed_preexisted = embed.is_symlink() or embed.exists()
        embed.mkdir(parents=True, exist_ok=True)
        managed = self._resolved_managed_paths(cfg.source_path, cfg.embed_profile)
        # Pending marker (R2-S7): written before any action so a crash is detectable.
        self.write_manifest(
            cfg.target_root,
            Manifest(
                method=effective,
                source_path=cfg.source_path,
                profiles=[p.lang for p in cfg.profiles],
                state=ManifestState.PENDING,
                embed_profile=cfg.embed_profile,
                managed_paths=managed,
            ),
        )
        has_subprocess = any(a.type is ActionType.RUN_SUBPROCESS for a in actions)
        applied: List[Action] = []
        # On a fresh install, rolling back removes the whole embed dir (and the pending
        # manifest); on a re-run we leave the pre-existing tree in place.
        newly_created: List[Path] = [] if embed_preexisted else [embed]
        owned_types = {
            ActionType.MKDIR,
            ActionType.SYMLINK,
            ActionType.WRITE_FILE,
            ActionType.COPY_FILE,
            ActionType.COPY_TREE,
        }
        try:
            for action in actions:
                self._confine(action.target, cfg.target_root)
                if action.is_satisfied():
                    self.logger.info(
                        "capdevpipe skip (already satisfied): %s", action.describe()
                    )
                    continue
                existed = action.target.is_symlink() or action.target.exists()
                self._apply_action(action, cfg)
                self._log_action(action)
                applied.append(action)
                if not existed and action.type in owned_types:
                    newly_created.append(action.target)
        except Exception as exc:  # noqa: BLE001 - rollback then report a clean result
            self.logger.error(
                "capdevpipe execute failed: %s",
                exc,
                extra={"pipeline_name": "capdevpipe_install"},
            )
            if has_subprocess:
                # External rsync writes cannot be cleanly reversed (R2-S2): repairable-only.
                return ExecuteResult(
                    success=False,
                    actions_applied=applied,
                    repairable=True,
                    error=str(exc),
                )
            self._rollback(newly_created)
            return ExecuteResult(
                success=False,
                actions_applied=applied,
                rolled_back=True,
                error=str(exc),
            )

        created_paths = [a.target for a in actions if a.type in owned_types]
        if effective is InstallMethod.COPY:
            # The rsync-produced files were not enumerated as actions; record the embed dir as
            # the copy-managed subtree so repair/drift/uninstall see them (R3-S2).
            created_paths.append(embed)
        manifest = Manifest(
            method=effective,
            source_path=cfg.source_path,
            created_paths=created_paths,
            profiles=[p.lang for p in cfg.profiles],
            state=ManifestState.COMPLETE,
            embed_profile=cfg.embed_profile,
            managed_paths=managed,
        )
        self.write_manifest(cfg.target_root, manifest)
        manifest_path = cfg.target_root / EMBED_DIR_NAME / MANIFEST_FILENAME
        return ExecuteResult(
            success=True, actions_applied=applied, manifest_path=manifest_path
        )

    def _rollback(self, newly_created: List[Path]) -> None:
        """Best-effort removal of paths this run created, newest first (FR-16)."""
        for path in reversed(newly_created):
            try:
                if path.is_symlink() or path.is_file():
                    path.unlink()
                elif path.is_dir():
                    shutil.rmtree(path)
            except OSError as exc:  # pragma: no cover - best effort
                self.logger.warning(
                    "capdevpipe rollback could not remove %s: %s", path, exc
                )

    # -- manifest (FR-18) -------------------------------------------------- #

    def _resolved_managed_paths(self, source: Path, profile: str) -> List[str]:
        """Top-level embed-dir entry names for *profile* — the canonical ``managed_paths`` set.

        Mirrors canonical ``ResolvedEmbedProfile.managed_paths()``: scripts + python aliases +
        packages + resource trees + copy_files, deduped and sorted. SDK-unique post-step
        artifacts (project-named wrapper, ``pipeline.env``, ``.gitignore``) are deliberately
        NOT included — they are tolerated extras under canonical verify, not managed paths
        (FR-A6, spike §0.2). Best-effort: on any resolution error, returns ``[]`` so the
        install still records a (canonical-shaped) manifest rather than crashing.
        """
        try:
            inv = resolve_embed_inventory(source, profile)
        except Exception as exc:  # noqa: BLE001 - manifest managed_paths are best-effort
            self.logger.warning("capdevpipe managed_paths resolution failed: %s", exc)
            return []
        names = [
            *inv.scripts,
            *inv.python_aliases,
            *inv.packages,
            *inv.resource_trees,
            *inv.copy_files,
        ]
        return sorted(set(names))

    def write_manifest(self, target: Path, manifest: Manifest) -> None:
        """Persist the install manifest to ``.cap-dev-pipe/.install-manifest.json`` (FR-18)."""
        embed_dir = target / EMBED_DIR_NAME
        embed_dir.mkdir(parents=True, exist_ok=True)
        path = embed_dir / MANIFEST_FILENAME
        path.write_text(json.dumps(manifest.to_dict(), indent=2), encoding="utf-8")
        self.logger.info(
            "capdevpipe manifest written: %s (%d paths, state=%s)",
            path,
            len(manifest.created_paths),
            manifest.state.value,
            extra={"pipeline_name": "capdevpipe_install"},
        )

    def read_manifest(self, target: Path) -> Optional[Manifest]:
        """Read the install manifest, or ``None`` if absent/unreadable (FR-18).

        Forward-compatible handling of an unknown ``manifest_version`` (graceful fallback)
        is added in P2 (R3-S5 / task #11); here a parse error degrades to ``None`` so callers
        re-derive from disk rather than crash.
        """
        path = target / EMBED_DIR_NAME / MANIFEST_FILENAME
        if not path.is_file():
            return None
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            version = int(data.get("manifest_version", MANIFEST_VERSION))
            if version > MANIFEST_VERSION:
                # Forward-compat (R3-S5): a manifest written by a newer installer may have an
                # unknown shape — degrade to re-derive-from-disk rather than mis-parse.
                self.logger.warning(
                    "capdevpipe: manifest at %s has version %d > supported %d; "
                    "re-deriving from disk",
                    path,
                    version,
                    MANIFEST_VERSION,
                )
                return None
            return Manifest.from_dict(data)
        except (json.JSONDecodeError, KeyError, ValueError, TypeError) as exc:
            self.logger.warning(
                "capdevpipe: unreadable manifest at %s (%s); re-deriving from disk",
                path,
                exc,
            )
            return None

    # -- builders (return Action slices composed by plan_actions) ---------- #
    #
    # Each builder below returns its slice of the single planned action list. They do NOT
    # touch the filesystem; ``execute`` applies the composed list idempotently (the
    # preview == execute-set invariant, R2-F4). Bodies are filled by tasks #4–#7.

    @staticmethod
    def wrapper_filename(name: str) -> str:
        """The project wrapper filename ``{name}-cap-dlv-pipe.sh`` (FR-8 / FR-14)."""
        return f"{name}-cap-dlv-pipe.sh"

    # -- embedding (FR-5, FR-6) -------------------------------------------- #

    #: Canonical ``EmbedActionType`` value → SDK ``ActionType`` (FR-A7 delegation).
    _EMBED_ACTION_MAP = {
        "mkdir": ActionType.MKDIR,
        "symlink": ActionType.SYMLINK,
        "copy_file": ActionType.COPY_FILE,
        "copy_tree": ActionType.COPY_TREE,
    }

    def embed_symlink(self, cfg: InstallConfig) -> List[Action]:
        """Actions to symlink the manifest-resolved embed set with absolute targets (FR-5).

        The *kind → action* mapping (which inventory entries are symlinked vs copied) is
        delegated to the canonical shared planner ``resolve_install_plan`` (FR-A7): the SDK
        no longer re-derives it, it translates the canonical plan to its own ``Action`` type.
        Script and package symlinks keep **absolute** ``source`` paths so ``dirname "$0"``
        resolves to the embedded dir (NFR-3); resource trees are copied locally.
        """
        source = Path(cfg.source_path).resolve()
        embed = Path(cfg.target_root) / EMBED_DIR_NAME
        plan = resolve_embed_plan(source, cfg.embed_profile, "symlink", cfg.target_root)
        actions: List[Action] = []
        for step in plan:
            action_type = self._EMBED_ACTION_MAP.get(step.action_type)
            if action_type is None:  # pragma: no cover - unknown canonical action kind
                raise ConfigurationError(
                    f"unsupported canonical embed action '{step.action_type}' — "
                    "cap-dev-pipe planner is newer than this SDK installer."
                )
            target = embed if step.target_rel == "." else embed / step.target_rel
            src = source / step.source_rel if step.source_rel else None
            actions.append(Action(type=action_type, target=target, source=src))
        return actions

    @staticmethod
    def _is_trusted_source(source: Path) -> bool:
        """Whether ``source`` is the default checkout (or under it) — trusted to execute (R3-S1)."""
        resolved = Path(source).resolve()
        default = DEFAULT_SOURCE.resolve()
        return resolved == default or default in resolved.parents

    def embed_copy(self, cfg: InstallConfig) -> List[Action]:
        """Action to shell out to ``install-cap-dev-pipe.sh --force-pipeline-env <target>``
        (FR-6). The rsync writes scripts/design/prompts/pipeline.env into the target.

        Because the copy method *executes* a script from a (possibly overridden) source, it
        refuses an untrusted source unless the caller explicitly opted in via
        ``cfg.trust_source`` — the TUI sets this after surfacing/confirming the exact script
        path (R3-S1 / NFR-6 code-execution confinement)."""
        source = Path(cfg.source_path).resolve()
        installer_script = source / "install-cap-dev-pipe.sh"
        if not installer_script.is_file():
            raise ConfigurationError(
                f"Copy install requires {installer_script}, which is missing. "
                f"Point to a complete cap-dev-pipe checkout."
            )
        if not (cfg.trust_source or self._is_trusted_source(source)):
            raise ConfigurationError(
                f"Refusing to execute {installer_script} from an untrusted source. The copy "
                f"method runs this script; confirm the source is trusted (set trust_source=True, "
                f"or use the default {DEFAULT_SOURCE})."
            )
        embed = Path(cfg.target_root) / EMBED_DIR_NAME
        return [
            Action(
                type=ActionType.RUN_SUBPROCESS,
                target=embed,
                cwd=source,
                argv=[
                    str(installer_script),
                    "--embed-profile",
                    cfg.embed_profile,
                    "--force-pipeline-env",
                    str(cfg.target_root),
                ],
            )
        ]

    def reconcile_copy_install(self, cfg: InstallConfig) -> List[Action]:
        """Post-rsync reconcile action (FR-6): merges only the four managed ``pipeline.env``
        keys into the rsync-written file (preserving non-managed keys, R3-F5) and removes the
        auto-linked root ``java`` profile so the TUI's profile step is the sole authority
        (exactly one profile dir per language). Applied at execute time because it depends on
        the rsync output."""
        embed = Path(cfg.target_root) / EMBED_DIR_NAME
        return [Action(type=ActionType.RECONCILE_COPY, target=embed)]

    # -- pipeline.env helpers (shared by reconcile #4 and write_pipeline_env #5) -- #

    def _require_managed_keys(self, cfg: InstallConfig) -> Dict[str, str]:
        """Return the four managed values, or block (FR-7, R2-S6): never write a blank.

        Detection (env → ConfigManager → walk-up) fills ``cfg.pipeline_env`` upstream (#5);
        this is the consumption guard that refuses to proceed on any still-empty key.
        """
        env = cfg.pipeline_env or {}
        missing = [k for k in MANAGED_ENV_KEYS if not (env.get(k) or "").strip()]
        if missing:
            raise ConfigurationError(
                f"Cannot write pipeline.env: no value for {', '.join(missing)}. Provide "
                f"{'these keys' if len(missing) > 1 else 'this key'} explicitly — the "
                f"installer will not write a blank that fails later at --list-langs."
            )
        return {k: env[k].strip() for k in MANAGED_ENV_KEYS}

    def _merge_managed_env(self, existing: str, managed: Dict[str, str]) -> str:
        """Merge the managed keys into ``existing`` text, preserving everything else (R3-F5).

        Each managed key is replaced in place if present (first occurrence) else appended;
        comments, blank lines, and non-managed keys pass through unchanged.

        Format note (do NOT "fix" to ``export KEY=`` or add shell-escaping): cap-dev-pipe's
        ``pipeline/config.py:load_pipeline_env`` parses this file as plain ``key=value`` via
        ``line.partition("=")`` and ``key.strip()`` — it does NOT shell-source it. An
        ``export `` prefix would be captured *into the key* (``"export CONTEXTCORE_ROOT"``),
        making the value unreadable; ``$``/spaces in values are stored literally and need no
        escaping. The bare ``KEY="value"`` form here matches the canonical ``write_env_templates``
        output exactly. The ``(export\\s+)?`` in the match below only tolerates a pre-existing
        ``export`` line, rewriting it to the canonical bare form.
        """
        seen: set = set()
        out: List[str] = []
        for line in existing.splitlines():
            matched = next(
                (
                    k
                    for k in MANAGED_ENV_KEYS
                    if re.match(rf"^\s*(export\s+)?{re.escape(k)}=", line)
                ),
                None,
            )
            if matched is not None:
                if matched not in seen:
                    out.append(f'{matched}="{managed[matched]}"')
                    seen.add(matched)
                # drop duplicate managed lines
            else:
                out.append(line)
        for key in MANAGED_ENV_KEYS:
            if key not in seen:
                out.append(f'{key}="{managed[key]}"')
        return "\n".join(out) + "\n"

    def _reconcile_copy(self, cfg: InstallConfig) -> None:
        """Apply-time copy reconcile (FR-6): managed-key merge into pipeline.env + drop java."""
        embed = Path(cfg.target_root) / EMBED_DIR_NAME
        env_path = embed / "pipeline.env"
        managed = self._require_managed_keys(cfg)
        existing = env_path.read_text(encoding="utf-8") if env_path.is_file() else ""
        env_path.write_text(
            self._merge_managed_env(existing, managed), encoding="utf-8"
        )
        os.chmod(env_path, 0o600)  # NFR-6
        java = embed / "java"
        if java.is_symlink():
            java.unlink()
        elif java.is_dir():
            shutil.rmtree(java)
        if not (java.is_symlink() or java.exists()):
            self.logger.info(
                "capdevpipe reconcile: pipeline.env managed keys merged; "
                "auto-linked java profile cleared (TUI profile step is authoritative)"
            )

    # -- configuration (FR-7, FR-8) ---------------------------------------- #

    def detect_pipeline_env(self, cfg: InstallConfig) -> Dict[str, str]:
        """Detect the four managed keys: env var → ConfigManager → walk-up (FR-7).

        ``PROJECT_ROOT``/``PROJECT_NAME`` derive from the target; ``CONTEXTCORE_ROOT``/
        ``SDK_ROOT`` come from the env var, then a remembered ConfigManager preference, then
        a walk-up search of the target's ancestors for a sibling checkout. Any explicit,
        non-blank value already in ``cfg.pipeline_env`` (e.g. user-confirmed) wins. Keys that
        cannot be detected are left blank so the consumption guard blocks (R2-S6) — the TUI
        handler prompts the user to fill them before writing.
        """
        target = Path(cfg.target_root).resolve()
        detected: Dict[str, str] = {
            "PROJECT_ROOT": str(target),
            "PROJECT_NAME": target.name,
            "CONTEXTCORE_ROOT": self._detect_root(
                "CONTEXTCORE_ROOT", "ContextCore", PREF_CONTEXTCORE_ROOT, target
            ),
            "SDK_ROOT": self._detect_root(
                "SDK_ROOT", "startd8-sdk", PREF_SDK_ROOT, target
            ),
        }
        for key, value in (cfg.pipeline_env or {}).items():
            if (value or "").strip():
                detected[key] = value.strip()
        return detected

    @staticmethod
    def _detect_root(env_key: str, dir_name: str, pref_key: str, target: Path) -> str:
        """Resolve a root path: env var → ConfigManager preference → ancestor walk-up."""
        env_val = os.getenv(env_key)
        if env_val:
            return env_val
        try:
            pref = get_config_manager().get_preference(pref_key)
        except (
            Exception
        ):  # pragma: no cover - config unavailable; fall through to walk-up
            pref = None
        if pref:
            return str(pref)
        for ancestor in [target, *target.parents]:
            candidate = ancestor / dir_name
            if candidate.is_dir():
                return str(candidate)
        return ""

    def write_pipeline_env(self, cfg: InstallConfig) -> List[Action]:
        """Action to write ``pipeline.env`` with the four managed keys, mode ``0600``
        (FR-7, NFR-6). Blocks (raises :class:`ConfigurationError`) rather than writing a
        blank for any undetectable key (R2-S6); merges into any existing file so user-added
        non-managed keys survive a re-run (R3-F5); writes no secrets (NFR-4)."""
        managed = self._require_managed_keys(cfg)
        env_path = Path(cfg.target_root) / EMBED_DIR_NAME / "pipeline.env"
        existing = (
            env_path.read_text(encoding="utf-8")
            if env_path.is_file()
            else PIPELINE_ENV_HEADER
        )
        return [
            Action(
                type=ActionType.WRITE_FILE,
                target=env_path,
                content=self._merge_managed_env(existing, managed),
                mode=0o600,
            )
        ]

    def generate_wrapper(self, cfg: InstallConfig) -> List[Action]:
        """Action to generate ``{name}-cap-dlv-pipe.sh`` from the template, mode ``0755``
        (FR-8). Substitutes ``{{PROJECT_NAME}}`` and ``{{DEFAULT_LANG}}``."""
        source = Path(cfg.source_path).resolve()
        template = source / WRAPPER_TEMPLATE_NAME
        if not template.is_file():
            raise ConfigurationError(
                f"Wrapper template not found at {template}. Point to a complete "
                f"cap-dev-pipe checkout (it ships {WRAPPER_TEMPLATE_NAME})."
            )
        name = (cfg.pipeline_env or {}).get("PROJECT_NAME") or Path(
            cfg.target_root
        ).name
        content = (
            template.read_text(encoding="utf-8")
            .replace("{{PROJECT_NAME}}", name)
            .replace("{{DEFAULT_LANG}}", cfg.default_lang)
        )
        wrapper = Path(cfg.target_root) / EMBED_DIR_NAME / self.wrapper_filename(name)
        return [
            Action(
                type=ActionType.WRITE_FILE, target=wrapper, content=content, mode=0o755
            )
        ]

    # -- profiles (FR-9) --------------------------------------------------- #

    @staticmethod
    def _is_review_artifact(path: Path) -> bool:
        """Exclude review artifacts from profile-doc detection (FR-9)."""
        if "arc-review" in (part.lower() for part in path.parts):
            return True
        name = path.name.lower()
        return name.startswith(("crp_", "crp-")) or "review" in name

    def detect_doc_candidates(self, target: Path) -> DocCandidates:
        """Detect plan/requirements docs in root and one-level ``docs/`` (FR-9).

        Matches ``*plan*.md`` / ``*requirements*.md`` case-insensitively, de-duplicated and
        deterministically ordered (by name then path), excluding review artifacts
        (``arc-review/``, ``CRP_*``, ``*REVIEW*``).
        """
        target = Path(target)
        plans: List[Path] = []
        reqs: List[Path] = []
        for directory in (target, target / "docs"):
            if not directory.is_dir():
                continue
            for doc in directory.glob("*.md"):
                if self._is_review_artifact(doc):
                    continue
                low = doc.name.lower()
                if "plan" in low:
                    plans.append(doc)
                if "requirement" in low:
                    reqs.append(doc)

        def _order(items: List[Path]) -> List[Path]:
            unique = {p.resolve(): p for p in items}
            return sorted(unique.values(), key=lambda p: (p.name.lower(), str(p)))

        return DocCandidates(plans=_order(plans), reqs=_order(reqs))

    def create_profile(self, cfg: InstallConfig, profile: ProfileSpec) -> List[Action]:
        """Action(s) to create ``<lang>/`` with ``<lang>-plan.md`` + ``<lang>-requirements.md``
        (FR-9). Profile doc links are **relative** (NFR-3) so a profile survives moving the
        project; the method (relative-symlink vs copy) comes from
        :meth:`_resolve_profile_method`."""
        embed = Path(cfg.target_root) / EMBED_DIR_NAME
        profile_dir = embed / profile.lang
        method = self._resolve_profile_method(cfg)
        actions: List[Action] = [Action(type=ActionType.MKDIR, target=profile_dir)]
        for doc, suffix in ((profile.plan, "plan"), (profile.reqs, "requirements")):
            if doc is None:
                continue
            link = profile_dir / f"{profile.lang}-{suffix}.md"
            doc_abs = Path(doc).resolve()
            if method is InstallMethod.SYMLINK:
                relative = Path(os.path.relpath(doc_abs, profile_dir.resolve()))
                actions.append(
                    Action(type=ActionType.SYMLINK, target=link, source=relative)
                )
            else:
                actions.append(
                    Action(type=ActionType.COPY_FILE, target=link, source=doc_abs)
                )
        return actions

    # -- gitignore / verify (FR-10, FR-11) --------------------------------- #

    def update_gitignore(self, cfg: InstallConfig) -> List[Action]:
        """Action to idempotently ensure ``.cap-dev-pipe/pipeline-output/`` is ignored
        (FR-10). Warns first if the target git repo has uncommitted changes (NFR-6)."""
        self._warn_if_repo_dirty(Path(cfg.target_root))
        gitignore = Path(cfg.target_root) / ".gitignore"
        return [
            Action(
                type=ActionType.GITIGNORE_ENSURE,
                target=gitignore,
                detail=f"{EMBED_DIR_NAME}/pipeline-output/",
            )
        ]

    def _warn_if_repo_dirty(self, target: Path) -> None:
        """Log a warning before mutating ``.gitignore`` in a dirty repo (NFR-6, best-effort)."""
        try:
            proc = subprocess.run(
                ["git", "status", "--porcelain"],
                cwd=str(target),
                capture_output=True,
                text=True,
                timeout=10,
            )
        except (OSError, subprocess.SubprocessError):
            return
        if proc.returncode == 0 and proc.stdout.strip():
            self.logger.warning(
                "capdevpipe: target git repo %s has uncommitted changes; .gitignore "
                "will be modified",
                target,
            )

    @staticmethod
    def _parse_listed_langs(stdout: str) -> List[str]:
        """Extract profile names from ``run.sh --list-langs`` output.

        The pipeline prints each profile as an indented ``<lang>/`` line under an
        "Available language profiles:" header, with ``plan:``/``reqs:`` detail lines
        beneath it. A profile name is therefore a stripped line that ends with ``/`` and
        contains no whitespace or ``:``; the header, the detail lines, and the
        no-profiles help text are all ignored. Returning bare names (not raw lines) lets
        :meth:`verify` test membership exactly instead of by substring — a substring test
        would, e.g., count ``go`` as present against a ``django/`` profile.
        """
        langs: List[str] = []
        for raw in stdout.splitlines():
            line = raw.strip()
            if not line.endswith("/"):
                continue
            name = line[:-1]
            if name and ":" not in name and not any(c.isspace() for c in name):
                langs.append(name)
        return langs

    def verify(self, target: Path) -> VerifyResult:
        """Verify the install by subprocess ``run.sh --list-langs`` (FR-11).

        Passes iff the subprocess exits 0, every created profile (per the manifest) appears
        in stdout, and the single-source property holds (local ``design/``+``prompts/`` and a
        resolvable ``run.sh`` in the embedded dir). A zero-profile "skip" install is a valid
        pass (R2-F7). A dangling embedded ``run.sh`` symlink is reported as a re-point
        diagnostic rather than a raw resolution error (basic FR-17; full doctor in P2).
        """
        embed = Path(target) / EMBED_DIR_NAME
        run_sh = embed / "run.sh"
        manifest = self.read_manifest(target)
        expected = manifest.profiles if manifest else []
        single_source_ok = (
            (embed / "design").is_dir()
            and (embed / "prompts").is_dir()
            and (run_sh.is_symlink() or run_sh.is_file())
        )
        if not (run_sh.is_symlink() or run_sh.is_file()):
            return VerifyResult(
                passed=False,
                expected_langs=expected,
                single_source_ok=False,
                message=f"Embedded run.sh not found at {run_sh}. Run install or repair.",
            )
        if run_sh.is_symlink() and not run_sh.exists():
            missing = Path(os.readlink(run_sh))
            return VerifyResult(
                passed=False,
                expected_langs=expected,
                single_source_ok=single_source_ok,
                dangling_source=missing,
                message=(
                    f"Embedded run.sh points at {missing}, which no longer exists — the "
                    f"cap-dev-pipe source likely moved. Re-point via `upgrade`."
                ),
            )
        proc = self._run_subprocess(
            [str(run_sh), "--list-langs"], cwd=embed, timeout=SUBPROCESS_TIMEOUT_VERIFY
        )
        listed = self._parse_listed_langs(proc.stdout)
        listed_set = set(listed)
        missing_profiles = [lang for lang in expected if lang not in listed_set]
        passed = proc.returncode == 0 and not missing_profiles and single_source_ok
        if passed:
            message = f"Verified: --list-langs ok; {len(expected)} profile(s) present."
        elif proc.returncode != 0:
            message = f"--list-langs exited {proc.returncode}: {proc.stderr.strip()}"
        elif missing_profiles:
            message = (
                f"Profiles missing from --list-langs: {', '.join(missing_profiles)}"
            )
        else:
            message = (
                "Single-source property failed: local design/prompts or run.sh missing."
            )
        return VerifyResult(
            passed=passed,
            listed_langs=listed,
            expected_langs=expected,
            single_source_ok=single_source_ok,
            exit_code=proc.returncode,
            stderr=proc.stderr,
            message=message,
        )

    # -- re-run (FR-12) ---------------------------------------------------- #

    def detect_existing(self, target: Path) -> InstallState:
        """Detect an existing install via the manifest + filesystem (FR-12)."""
        embed = Path(target) / EMBED_DIR_NAME
        if not (embed.exists() or embed.is_symlink()):
            return InstallState(exists=False)
        manifest = self.read_manifest(target)
        pending = manifest is not None and manifest.state is ManifestState.PENDING
        broken = [
            p for p in sorted(embed.glob("*")) if p.is_symlink() and not p.exists()
        ]
        return InstallState(
            exists=True, manifest=manifest, pending=pending, broken_symlinks=broken
        )

    def orphan_symlink_candidates(self, target: Path, cfg: InstallConfig) -> List[Path]:
        """Embed symlinks NOT in the current inventory — what ``upgrade`` would prune (read-only).

        Extracted so a ``--dry-run`` can preview the prune set without unlinking anything.
        """
        embed = Path(target) / EMBED_DIR_NAME
        inventory = resolve_embed_inventory(cfg.source_path, cfg.embed_profile)
        valid = inventory.symlink_top_level_names()
        return [
            entry
            for entry in (sorted(embed.iterdir()) if embed.is_dir() else [])
            if entry.is_symlink() and entry.name not in valid
        ]

    def _prune_orphan_symlinks(self, target: Path, cfg: InstallConfig) -> None:
        """Remove embed symlinks whose script was deleted upstream so embed == source (R2-F6)."""
        for entry in self.orphan_symlink_candidates(target, cfg):
            entry.unlink()
            self.logger.info("capdevpipe upgrade: pruned orphaned symlink %s", entry)

    def apply_mode(self, target: Path, mode: ReRunMode, cfg: InstallConfig) -> None:
        """Apply a re-run mode with a defined per-file change set (FR-12).

        - ``reconfigure``: rewrite config (pipeline.env, wrapper, profiles, gitignore);
          leave embedded scripts untouched.
        - ``upgrade``: refresh script embedding and prune symlinks orphaned by upstream
          deletions (R2-F6); keep config + profiles.
        - ``repair``: idempotently replay the full plan (only missing/incorrect entries
          change), then verify.
        - ``replace-pipeline.env``: rewrite only ``pipeline.env`` (managed keys; non-managed
          preserved, R3-F5).

        ``doctor`` (source-relocation, FR-17) is added in P2 (#16).
        """
        if mode is ReRunMode.REPAIR:
            self._run_actions(self.plan_actions(cfg), cfg)
            result = self.verify(target)
            if not result.passed:
                self.logger.warning(
                    "capdevpipe repair: verify failed — %s", result.message
                )
            return
        effective = self._effective_method(cfg)
        if mode is ReRunMode.RECONFIGURE:
            actions: List[Action] = []
            if effective is InstallMethod.SYMLINK:
                actions += self.write_pipeline_env(cfg)
            else:
                actions += self.reconcile_copy_install(cfg)
            actions += self.generate_wrapper(cfg)
            for profile in cfg.profiles:
                actions += self.create_profile(cfg, profile)
            actions += self.update_gitignore(cfg)
            self._run_actions(actions, cfg)
            return
        if mode is ReRunMode.UPGRADE:
            if effective is InstallMethod.SYMLINK:
                self._run_actions(self.embed_symlink(cfg), cfg)
            else:
                self._run_actions(
                    self.embed_copy(cfg) + self.reconcile_copy_install(cfg), cfg
                )
            self._prune_orphan_symlinks(target, cfg)
            return
        if mode is ReRunMode.REPLACE_PIPELINE_ENV:
            if effective is InstallMethod.SYMLINK:
                self._run_actions(self.write_pipeline_env(cfg), cfg)
            else:
                self._run_actions(self.reconcile_copy_install(cfg), cfg)
            return
        if mode is ReRunMode.DOCTOR:
            result = self.doctor(target)
            if not result.passed:
                self.logger.warning("capdevpipe doctor: %s", result.message)
            return
        raise NotImplementedError(
            f"apply_mode({mode.value}) is not a known re-run mode"
        )

    def doctor(self, target: Path) -> VerifyResult:
        """Health-check for a source-relocated symlink install (FR-17 / R2-S4).

        Detects a **dangling canonical source** — the absolute path the embedded script
        symlinks point at has moved/been deleted — and returns a re-point diagnostic naming
        the missing path rather than a raw resolution error. Falls through to :meth:`verify`
        when the source is intact.
        """
        embed = Path(target) / EMBED_DIR_NAME
        manifest = self.read_manifest(target)
        if manifest is not None and not Path(manifest.source_path).exists():
            return VerifyResult(
                passed=False,
                dangling_source=Path(manifest.source_path),
                message=(
                    f"Canonical source {manifest.source_path} no longer exists — it was "
                    f"moved or deleted. Re-point via `upgrade` with the new source path."
                ),
            )
        dangling = [
            p
            for p in (sorted(embed.glob("*")) if embed.is_dir() else [])
            if p.is_symlink() and not p.exists()
        ]
        if dangling:
            missing = Path(os.readlink(dangling[0]))
            return VerifyResult(
                passed=False,
                dangling_source=missing,
                message=(
                    f"Embedded symlink {dangling[0].name} points at {missing}, which is "
                    f"gone — the cap-dev-pipe source likely moved. Re-point via `upgrade`."
                ),
            )
        return self.verify(target)
