"""Forward Manifest Validation against an extracted ManifestRegistry.

This module compares a prescribed `ForwardManifest` (Phase 3) against the actual
codebase represented by a `ManifestRegistry` (Phase 1). It computes structural
and semantic violations (`ContractViolation`), emitting warnings for advisory
breaches and errors for mandatory omissions (e.g. missing API endpoints or
function signatures).
"""

import ast
import logging
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional, List

from startd8.forward_manifest import ForwardManifest, InterfaceContract, ForwardFileSpec
from startd8.utils.manifest_registry import ManifestRegistry, _flatten_elements
from startd8.utils.code_manifest import ElementKind

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class ContractViolation:
    """A structural or semantic divergence between prescribed contracts and generated code."""
    contract_id: str
    violation_type: str
    expected: str
    actual: Optional[str] = None
    file_path: Optional[str] = None
    severity: str = "error"  # "error" for mandatory structures, "warning" for advisory formulas.


def validate_forward_manifest(
    manifest: ForwardManifest,
    registry: ManifestRegistry,
) -> List[ContractViolation]:
    """Validates generated code topology against front-loaded contracts.

    Args:
        manifest: The prescribed target topography of the project.
        registry: The actual source code topography generated by Artisan.

    Returns:
        List[ContractViolation]: List of anomalies detected, containing expected
        values, actual values, and severity mappings.
    """
    violations: List[ContractViolation] = []

    # 1. Validate File Specifications
    for file_path, spec in manifest.file_specs.items():
        violations.extend(_validate_file_spec(file_path, spec, registry))

    # 2. Validate Abstract Contracts
    for contract in manifest.contracts:
        violations.extend(_validate_contract(contract, registry))

    return violations


def _validate_file_spec(
    file_path: str,
    spec: ForwardFileSpec,
    registry: ManifestRegistry,
) -> List[ContractViolation]:
    """Verify that a specific file exists and contains prescribed elements."""
    violations: List[ContractViolation] = []
    
    file_manifest = registry.get(file_path)
    if not file_manifest:
        violations.append(
            ContractViolation(
                contract_id=f"file_exists:{file_path}",
                violation_type="missing_file",
                expected="File exists in project",
                file_path=file_path,
                severity="error",
            )
        )
        return violations

    elements = _flatten_elements(file_manifest.elements)

    # Validate elements
    if spec.elements:
        actual_names = {e.name for e in elements}
        for expected_el in spec.elements:
            if expected_el.name not in actual_names:
                violations.append(
                    ContractViolation(
                        contract_id=f"file_element:{file_path}:{expected_el.name}",
                        violation_type=f"missing_{expected_el.kind.value}",
                        expected=f"Element `{expected_el.name}` of kind `{expected_el.kind.value}`",
                        actual="Not found",
                        file_path=file_path,
                        severity="error",
                    )
                )

    # Validate required imports
    if spec.imports:
        actual_imports = [imp.module for imp in (file_manifest.imports or [])]
        for req_imp in spec.imports:
            found = any(
                acc_imp == req_imp.module or acc_imp.startswith(req_imp.module + ".")
                for acc_imp in actual_imports
            )
            if not found:
                 violations.append(
                    ContractViolation(
                        contract_id=f"file_import:{file_path}:{req_imp.module}",
                        violation_type="missing_import",
                        expected=f"Module import `{req_imp.module}`",
                        actual="Not found",
                        file_path=file_path,
                        severity="error",
                    )
                )

    return violations


def _validate_contract(
    contract: InterfaceContract,
    registry: ManifestRegistry,
) -> List[ContractViolation]:
    """Routes specific contract categories to specific structural checkers."""
    violations: List[ContractViolation] = []

    if contract.category == "function_name":
        violations.extend(_validate_function_name(contract, registry))
    elif contract.category == "class_name":
        violations.extend(_validate_class_name(contract, registry))
    elif contract.category == "import_path":
        violations.extend(_validate_import_path(contract, registry))
    elif contract.category in ("formula", "render_pattern"):
        violations.extend(_validate_advisory(contract, registry))
    else:
        logger.debug(f"Validator skipped unsupported category: {contract.category}")

    return violations


def _validate_function_name(
    contract: InterfaceContract, registry: ManifestRegistry
) -> List[ContractViolation]:
    """Assert a function FQN exists and validates signature if provided."""
    violations: List[ContractViolation] = []
    
    if not contract.function_name:
        return violations

    # Determine standard FQN or perform broader regex extraction for methods
    fqn = contract.function_name
    match = registry.resolve_fqn(fqn)
    
    if match is None:
        violations.append(
            ContractViolation(
                contract_id=contract.contract_id,
                violation_type="missing_function",
                expected=f"Function `{fqn}` exists in project",
                severity="error",
            )
        )
        return violations
        
    file_path, element = match

    # Check if signature was strictly mandated via 'binding_text'
    if getattr(contract, "binding_text", "") and element.signature:
        expected_sig = contract.binding_text
        
        # Simple heuristic check if return signature provided in binding_text
        if "->" in expected_sig:
             expected_ret = expected_sig.split("->")[-1].strip()
             actual_ret = element.signature.return_annotation or "None"
             
             if expected_ret != actual_ret:
                  violations.append(
                      ContractViolation(
                          contract_id=contract.contract_id,
                          violation_type="signature_mismatch",
                          expected=f"Return type `{expected_ret}`",
                          actual=f"Return type `{actual_ret}`",
                          file_path=file_path,
                          severity="error",
                      )
                  )

    return violations


def _validate_class_name(
    contract: InterfaceContract, registry: ManifestRegistry
) -> List[ContractViolation]:
    """Assert a class exists, and its structural base class hierarchy is correct."""
    violations: List[ContractViolation] = []
    if not contract.class_name:
        return violations
        
    fqn = contract.class_name
    match = registry.resolve_fqn(fqn)
    
    if match is None:
        violations.append(
            ContractViolation(
                contract_id=contract.contract_id,
                violation_type="missing_class",
                expected=f"Class `{fqn}` exists in project",
                severity="error",
            )
        )
        return violations
        
    file_path, element = match
    
    # Assert inheritance requirements if set
    if contract.base_class:
        expected_parent = contract.base_class
        actual_bases = element.bases or []
        
        if expected_parent not in actual_bases:
            violations.append(
                ContractViolation(
                    contract_id=contract.contract_id,
                    violation_type="missing_base_class",
                    expected=f"Class `{fqn}` inherits from `{expected_parent}`",
                    actual=f"Bases: {actual_bases}",
                    file_path=file_path,
                    severity="error",
                )
            )
            
    return violations


def _validate_import_path(
    contract: InterfaceContract, registry: ManifestRegistry
) -> List[ContractViolation]:
    """Scan all FileManifest structures asserting no forbidden files are missing."""
    violations: List[ContractViolation] = []
    
    if not contract.target_path:
        return violations
        
    req_lib = contract.target_path
    
    for file_path, file_manifest in registry._manifest_map.items():
        actual_imports = [imp.module for imp in (file_manifest.imports or [])]
        found = any(req_lib in acc_imp for acc_imp in actual_imports)
        
        # We need more context on *where* the import path is required. 
        # Generally, it's global to the project if not specified for a file.
        # But for pipeline validation, if this lib is not imported anywhere, the feature may be omitted.
    
    # Check if we searched all files and found nothing
    # Actually, import_path contracts are usually globally verified:
    global_imports = set()
    for file_manifest in registry._manifest_map.values():
        for imp in (file_manifest.imports or []):
             global_imports.add(imp.module)
             
    if not any(
        acc_imp == req_lib or acc_imp.startswith(req_lib + ".")
        for acc_imp in global_imports
    ):
         violations.append(
             ContractViolation(
                 contract_id=contract.contract_id,
                 violation_type="missing_dependency",
                 expected=f"Dependency `{req_lib}` is utilized in the codebase",
                 actual="Not found in any imports",
                 severity="error",
             )
         )

    return violations


def _validate_advisory(
    contract: InterfaceContract, registry: ManifestRegistry
) -> List[ContractViolation]:
    """Validate formulas and UI render templates. Treat failures as warnings."""
    # Since formulas are deeply semantic (e.g. "Calculate MRR where X > 0"),
    # we can't reliably structurally lint this without LLMs.
    # We yield a warning to alert agents that this contract could be breached.
    return [
         ContractViolation(
             contract_id=contract.contract_id,
             violation_type=f"unverified_{contract.category.value}",
             expected=f"Formula or Pattern `{contract.description}` verified",
             severity="warning",
             actual="Manual verification required",
         )
    ]


# ---------------------------------------------------------------------------
# Disk compliance validation (Phase B — Kaizen Quality)
# ---------------------------------------------------------------------------


@dataclass
class DiskComplianceResult:
    """Post-assembly disk validation result for a single file."""

    file_path: str
    ast_valid: bool = True
    stubs_remaining: int = 0
    duplicate_definitions: int = 0
    import_completeness: float = 1.0
    contract_compliance: float = 1.0
    contract_violations: List[ContractViolation] = field(default_factory=list)
    semantic_issues: List[Any] = field(default_factory=list)
    error: Optional[str] = None


def validate_disk_compliance(
    file_path: str,
    project_root: str,
    manifest: Optional[ForwardManifest] = None,
) -> DiskComplianceResult:
    """Validate the file on disk against forward manifest after assembly.

    Produces a structured compliance result that feeds post-mortem scoring.
    Only processes Python files.

    Args:
        file_path: Relative or absolute path to the file.
        project_root: Project root directory.
        manifest: Optional forward manifest for contract compliance.

    Returns:
        DiskComplianceResult with stubs, duplicates, import completeness, etc.
    """
    result = DiskComplianceResult(file_path=file_path)

    abs_path = Path(project_root) / file_path
    if not abs_path.is_file():
        result.ast_valid = False
        result.error = "file_not_found"
        return result

    if abs_path.suffix != ".py":
        return result

    try:
        source = abs_path.read_text(encoding="utf-8")
    except OSError as exc:
        result.ast_valid = False
        result.error = f"read_error: {exc}"
        return result

    # AST validity
    try:
        tree = ast.parse(source)
    except SyntaxError as exc:
        result.ast_valid = False
        result.error = f"syntax_error: {exc}"
        return result

    # Count stubs: raise NotImplementedError / bare pass in function/method bodies
    result.stubs_remaining = _count_stubs(tree)

    # Count duplicate definitions at module level
    result.duplicate_definitions = _count_duplicate_definitions(tree)

    # Contract compliance via manifest
    if manifest and file_path in manifest.file_specs:
        spec = manifest.file_specs[file_path]
        violations = _validate_disk_file_against_spec(tree, spec, file_path)
        result.contract_violations = violations

        total_checks = len(spec.elements or []) + len(spec.imports or [])
        if total_checks > 0:
            error_violations = sum(1 for v in violations if v.severity == "error")
            result.contract_compliance = max(
                0.0, 1.0 - (error_violations / total_checks)
            )

        # Import completeness
        if spec.imports:
            actual_imports = _extract_import_modules(tree)
            matched = sum(
                1 for req_imp in spec.imports
                if any(
                    ai == req_imp.module or ai.startswith(req_imp.module + ".")
                    for ai in actual_imports
                )
            )
            result.import_completeness = matched / len(spec.imports)

    return result


def _count_stubs(tree: ast.AST) -> int:
    """Count stub bodies (raise NotImplementedError or bare pass) in functions."""
    count = 0
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            body = node.body
            # Strip leading docstring
            if (
                body
                and isinstance(body[0], ast.Expr)
                and isinstance(body[0].value, (ast.Constant, ast.Str))
            ):
                body = body[1:]
            if len(body) == 1:
                stmt = body[0]
                # bare pass
                if isinstance(stmt, ast.Pass):
                    count += 1
                # raise NotImplementedError
                elif isinstance(stmt, ast.Raise) and stmt.exc is not None:
                    if isinstance(stmt.exc, ast.Call):
                        func = stmt.exc.func
                        if isinstance(func, ast.Name) and func.id == "NotImplementedError":
                            count += 1
                    elif isinstance(stmt.exc, ast.Name) and stmt.exc.id == "NotImplementedError":
                        count += 1
    return count


def _count_duplicate_definitions(tree: ast.AST) -> int:
    """Count duplicate function/class names at module level only."""
    names: List[str] = []
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            names.append(node.name)
    seen: set = set()
    dupes = 0
    for name in names:
        if name in seen:
            dupes += 1
        seen.add(name)
    return dupes


def _extract_import_modules(tree: ast.AST) -> List[str]:
    """Extract all imported module names from an AST."""
    modules: List[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                modules.append(alias.name)
        elif isinstance(node, ast.ImportFrom):
            if node.module:
                modules.append(node.module)
    return modules


def _validate_disk_file_against_spec(
    tree: ast.AST,
    spec: ForwardFileSpec,
    file_path: str,
) -> List[ContractViolation]:
    """Check disk AST against forward manifest spec (simplified, no registry)."""
    violations: List[ContractViolation] = []

    # Check elements exist
    if spec.elements:
        actual_names: set = set()
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                actual_names.add(node.name)
        for expected_el in spec.elements:
            if expected_el.name not in actual_names:
                violations.append(ContractViolation(
                    contract_id=f"disk:{file_path}:{expected_el.name}",
                    violation_type=f"missing_{expected_el.kind.value}",
                    expected=f"Element `{expected_el.name}`",
                    actual="Not found on disk",
                    file_path=file_path,
                    severity="error",
                ))

    # Check imports
    if spec.imports:
        actual_imports = _extract_import_modules(tree)
        for req_imp in spec.imports:
            found = any(
                ai == req_imp.module or ai.startswith(req_imp.module + ".")
                for ai in actual_imports
            )
            if not found:
                violations.append(ContractViolation(
                    contract_id=f"disk_import:{file_path}:{req_imp.module}",
                    violation_type="missing_import",
                    expected=f"Import `{req_imp.module}`",
                    actual="Not found on disk",
                    file_path=file_path,
                    severity="error",
                ))

    return violations
