"""Forward Manifest Validation against an extracted ManifestRegistry.

This module compares a prescribed `ForwardManifest` (Phase 3) against the actual
codebase represented by a `ManifestRegistry` (Phase 1). It computes structural
and semantic violations (`ContractViolation`), emitting warnings for advisory
breaches and errors for mandatory omissions (e.g. missing API endpoints or
function signatures).
"""

import ast
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional, List, Set

from startd8.forward_manifest import ForwardManifest, InterfaceContract, ForwardFileSpec
from startd8.logging_config import get_logger
from startd8.utils.manifest_registry import ManifestRegistry, _flatten_elements
from startd8.utils.code_manifest import ElementKind

logger = get_logger(__name__)


@dataclass(frozen=True)
class ContractViolation:
    """A structural or semantic divergence between prescribed contracts and generated code."""
    contract_id: str
    violation_type: str
    expected: str
    actual: Optional[str] = None
    file_path: Optional[str] = None
    severity: str = "error"  # "error" for mandatory structures, "warning" for advisory formulas.


def validate_forward_manifest(
    manifest: ForwardManifest,
    registry: ManifestRegistry,
) -> List[ContractViolation]:
    """Validates generated code topology against front-loaded contracts.

    Args:
        manifest: The prescribed target topography of the project.
        registry: The actual source code topography generated by Artisan.

    Returns:
        List[ContractViolation]: List of anomalies detected, containing expected
        values, actual values, and severity mappings.
    """
    violations: List[ContractViolation] = []

    # 1. Validate File Specifications
    for file_path, spec in manifest.file_specs.items():
        violations.extend(_validate_file_spec(file_path, spec, registry))

    # 2. Validate Abstract Contracts
    for contract in manifest.contracts:
        violations.extend(_validate_contract(contract, registry))

    return violations


def _validate_file_spec(
    file_path: str,
    spec: ForwardFileSpec,
    registry: ManifestRegistry,
) -> List[ContractViolation]:
    """Verify that a specific file exists and contains prescribed elements."""
    violations: List[ContractViolation] = []
    
    file_manifest = registry.get(file_path)
    if not file_manifest:
        violations.append(
            ContractViolation(
                contract_id=f"file_exists:{file_path}",
                violation_type="missing_file",
                expected="File exists in project",
                file_path=file_path,
                severity="error",
            )
        )
        return violations

    elements = _flatten_elements(file_manifest.elements)

    # Validate elements
    if spec.elements:
        actual_names = {e.name for e in elements}
        for expected_el in spec.elements:
            if expected_el.name not in actual_names:
                violations.append(
                    ContractViolation(
                        contract_id=f"file_element:{file_path}:{expected_el.name}",
                        violation_type=f"missing_{expected_el.kind.value}",
                        expected=f"Element `{expected_el.name}` of kind `{expected_el.kind.value}`",
                        actual="Not found",
                        file_path=file_path,
                        severity="error",
                    )
                )

    # Validate required imports
    if spec.imports:
        actual_imports = [imp.module for imp in (file_manifest.imports or [])]
        for req_imp in spec.imports:
            found = any(
                acc_imp == req_imp.module or acc_imp.startswith(req_imp.module + ".")
                for acc_imp in actual_imports
            )
            if not found:
                 violations.append(
                    ContractViolation(
                        contract_id=f"file_import:{file_path}:{req_imp.module}",
                        violation_type="missing_import",
                        expected=f"Module import `{req_imp.module}`",
                        actual="Not found",
                        file_path=file_path,
                        severity="error",
                    )
                )

    return violations


def _validate_contract(
    contract: InterfaceContract,
    registry: ManifestRegistry,
) -> List[ContractViolation]:
    """Routes specific contract categories to specific structural checkers."""
    violations: List[ContractViolation] = []

    if contract.category == "function_name":
        violations.extend(_validate_function_name(contract, registry))
    elif contract.category == "class_name":
        violations.extend(_validate_class_name(contract, registry))
    elif contract.category == "import_path":
        violations.extend(_validate_import_path(contract, registry))
    elif contract.category in ("formula", "render_pattern"):
        violations.extend(_validate_advisory(contract, registry))
    else:
        logger.debug(f"Validator skipped unsupported category: {contract.category}")

    return violations


def _validate_function_name(
    contract: InterfaceContract, registry: ManifestRegistry
) -> List[ContractViolation]:
    """Assert a function FQN exists and validates signature if provided."""
    violations: List[ContractViolation] = []
    
    if not contract.function_name:
        return violations

    # Determine standard FQN or perform broader regex extraction for methods
    fqn = contract.function_name
    match = registry.resolve_fqn(fqn)
    
    if match is None:
        violations.append(
            ContractViolation(
                contract_id=contract.contract_id,
                violation_type="missing_function",
                expected=f"Function `{fqn}` exists in project",
                severity="error",
            )
        )
        return violations
        
    file_path, element = match

    # Check if signature was strictly mandated via 'binding_text'
    if getattr(contract, "binding_text", "") and element.signature:
        expected_sig = contract.binding_text
        
        # Simple heuristic check if return signature provided in binding_text
        if "->" in expected_sig:
             expected_ret = expected_sig.split("->")[-1].strip()
             actual_ret = element.signature.return_annotation or "None"
             
             if expected_ret != actual_ret:
                  violations.append(
                      ContractViolation(
                          contract_id=contract.contract_id,
                          violation_type="signature_mismatch",
                          expected=f"Return type `{expected_ret}`",
                          actual=f"Return type `{actual_ret}`",
                          file_path=file_path,
                          severity="error",
                      )
                  )

    return violations


def _validate_class_name(
    contract: InterfaceContract, registry: ManifestRegistry
) -> List[ContractViolation]:
    """Assert a class exists, and its structural base class hierarchy is correct."""
    violations: List[ContractViolation] = []
    if not contract.class_name:
        return violations
        
    fqn = contract.class_name
    match = registry.resolve_fqn(fqn)
    
    if match is None:
        violations.append(
            ContractViolation(
                contract_id=contract.contract_id,
                violation_type="missing_class",
                expected=f"Class `{fqn}` exists in project",
                severity="error",
            )
        )
        return violations
        
    file_path, element = match
    
    # Assert inheritance requirements if set
    if contract.base_class:
        expected_parent = contract.base_class
        actual_bases = element.bases or []
        
        if expected_parent not in actual_bases:
            violations.append(
                ContractViolation(
                    contract_id=contract.contract_id,
                    violation_type="missing_base_class",
                    expected=f"Class `{fqn}` inherits from `{expected_parent}`",
                    actual=f"Bases: {actual_bases}",
                    file_path=file_path,
                    severity="error",
                )
            )
            
    return violations


def _validate_import_path(
    contract: InterfaceContract, registry: ManifestRegistry
) -> List[ContractViolation]:
    """Scan all FileManifest structures asserting no forbidden files are missing."""
    violations: List[ContractViolation] = []
    
    if not contract.target_path:
        return violations
        
    req_lib = contract.target_path
    
    for file_path, file_manifest in registry._manifest_map.items():
        actual_imports = [imp.module for imp in (file_manifest.imports or [])]
        found = any(req_lib in acc_imp for acc_imp in actual_imports)
        
        # We need more context on *where* the import path is required. 
        # Generally, it's global to the project if not specified for a file.
        # But for pipeline validation, if this lib is not imported anywhere, the feature may be omitted.
    
    # Check if we searched all files and found nothing
    # Actually, import_path contracts are usually globally verified:
    global_imports = set()
    for file_manifest in registry._manifest_map.values():
        for imp in (file_manifest.imports or []):
             global_imports.add(imp.module)
             
    if not any(
        acc_imp == req_lib or acc_imp.startswith(req_lib + ".")
        for acc_imp in global_imports
    ):
         violations.append(
             ContractViolation(
                 contract_id=contract.contract_id,
                 violation_type="missing_dependency",
                 expected=f"Dependency `{req_lib}` is utilized in the codebase",
                 actual="Not found in any imports",
                 severity="error",
             )
         )

    return violations


def _validate_advisory(
    contract: InterfaceContract, registry: ManifestRegistry
) -> List[ContractViolation]:
    """Validate formulas and UI render templates. Treat failures as warnings."""
    # Since formulas are deeply semantic (e.g. "Calculate MRR where X > 0"),
    # we can't reliably structurally lint this without LLMs.
    # We yield a warning to alert agents that this contract could be breached.
    return [
         ContractViolation(
             contract_id=contract.contract_id,
             violation_type=f"unverified_{contract.category.value}",
             expected=f"Formula or Pattern `{contract.description}` verified",
             severity="warning",
             actual="Manual verification required",
         )
    ]


# ---------------------------------------------------------------------------
# Disk compliance validation (Phase B — Kaizen Quality)
# ---------------------------------------------------------------------------


@dataclass
class DiskComplianceResult:
    """Post-assembly disk validation result for a single file."""

    file_path: str
    ast_valid: bool = True
    stubs_remaining: int = 0
    duplicate_definitions: int = 0
    import_completeness: float = 1.0
    contract_compliance: float = 1.0
    contract_violations: List[ContractViolation] = field(default_factory=list)
    semantic_issues: List[Any] = field(default_factory=list)
    error: Optional[str] = None


def validate_disk_compliance(
    file_path: str,
    project_root: str,
    manifest: Optional[ForwardManifest] = None,
    *,
    sibling_files: Optional[List[str]] = None,
    sibling_imports: Optional[Dict[str, Set[str]]] = None,
    import_map: Optional[Dict[str, str]] = None,
    factory_patterns: Optional[List[str]] = None,
) -> DiskComplianceResult:
    """Validate the file on disk against forward manifest after assembly.

    Produces a structured compliance result that feeds post-mortem scoring.
    Only processes Python files.

    Args:
        file_path: Relative or absolute path to the file.
        project_root: Project root directory.
        manifest: Optional forward manifest for contract compliance.
        sibling_files: Optional list of sibling file paths for import
            resolution.  When absent the validator scans the parent
            directory on disk.
        sibling_imports: Optional mapping of sibling file path to import
            sets.  Used by L5 requirements cross-check to verify that
            every package in ``requirements.in`` is actually imported.
        import_map: Optional golden-seed import map (REQ-GS-302).
            When provided, import resolution operates in closed-world
            mode — any import not in the map is an error.
        factory_patterns: Optional list of regex patterns for factory
            function names (L4).  Defaults to ``create_*``, ``make_*``,
            ``build_*``, ``*_factory``.

    Returns:
        DiskComplianceResult with stubs, duplicates, import completeness, etc.
    """
    result = DiskComplianceResult(file_path=file_path)

    abs_path = Path(project_root) / file_path
    if not abs_path.is_file():
        result.ast_valid = False
        result.error = "file_not_found"
        return result

    # Non-Python file validators (KZ-Q4)
    if abs_path.suffix != ".py":
        return _validate_non_python_file(
            abs_path, result, sibling_imports=sibling_imports,
        )

    try:
        source = abs_path.read_text(encoding="utf-8")
    except OSError as exc:
        result.ast_valid = False
        result.error = f"read_error: {exc}"
        return result

    # AST validity
    try:
        tree = ast.parse(source)
    except SyntaxError as exc:
        result.ast_valid = False
        result.error = f"syntax_error: {exc}"
        return result

    # Count stubs: raise NotImplementedError / bare pass in function/method bodies
    result.stubs_remaining = _count_stubs(tree)

    # Count duplicate definitions at module level
    result.duplicate_definitions = _count_duplicate_definitions(tree)

    # --- Semantic validation (REQ-SV-200) ---
    # Only runs when the AST parsed successfully.

    # L1: Import resolution (REQ-SV-201)
    import_issues = _validate_import_resolution(
        tree, file_path, project_root,
        sibling_files=sibling_files,
        import_map=import_map,
    )
    result.semantic_issues.extend(import_issues)

    # L2: Cross-scope duplicate detection (REQ-SV-301)
    scope_dupe_issues = _detect_cross_scope_duplicates(tree)
    result.semantic_issues.extend(scope_dupe_issues)

    # L4: Factory return value check (REQ-SV-501)
    factory_issues = _validate_factory_returns(tree, patterns=factory_patterns)
    result.semantic_issues.extend(factory_issues)

    # L6: Discarded return value detection (REQ-SV-701)
    discarded_issues = _validate_discarded_returns(tree)
    result.semantic_issues.extend(discarded_issues)

    # L8: Service identity mismatch (REQ-SV2-400)
    identity_issues = _validate_service_identity(tree, file_path, sibling_files)
    result.semantic_issues.extend(identity_issues)

    # L9: Method resolution — self.x() where x is module-level, not a method (REQ-SV2-500)
    method_issues = _validate_method_resolution(tree)
    result.semantic_issues.extend(method_issues)

    # L10: Dead code — module-level functions never called within the file (REQ-SV2-600)
    reachability_issues = _validate_reachability(tree)
    result.semantic_issues.extend(reachability_issues)

    # --- Semantic issue logging and OTel (REQ-SV-901/902) ---
    _emit_semantic_observability(result, file_path, import_map)

    # Contract compliance via manifest
    if manifest and file_path in manifest.file_specs:
        spec = manifest.file_specs[file_path]
        violations = _validate_disk_file_against_spec(tree, spec, file_path)
        result.contract_violations = violations

        total_checks = len(spec.elements or []) + len(spec.imports or [])
        if total_checks > 0:
            error_violations = sum(1 for v in violations if v.severity == "error")
            result.contract_compliance = max(
                0.0, 1.0 - (error_violations / total_checks)
            )

        # Import completeness
        if spec.imports:
            actual_imports = _extract_import_modules(tree)
            matched = sum(
                1 for req_imp in spec.imports
                if any(
                    ai == req_imp.module or ai.startswith(req_imp.module + ".")
                    for ai in actual_imports
                )
            )
            result.import_completeness = matched / len(spec.imports)

    return result


def _validate_non_python_file(
    abs_path: Path,
    result: DiskComplianceResult,
    *,
    sibling_imports: Optional[Dict[str, Set[str]]] = None,
) -> DiskComplianceResult:
    """Lightweight validators for non-Python files (KZ-Q4).

    Prevents false-positive 1.0 scores on files like ``requirements.in``
    that contain function names instead of packages, or malformed
    Dockerfiles/YAML/JSON.
    """
    try:
        content = abs_path.read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        result.ast_valid = False
        result.error = f"read_error: {exc}"
        return result

    suffix = abs_path.suffix.lower()
    name = abs_path.name.lower()

    if suffix == ".in" or name == "requirements.txt":
        result = _validate_requirements_file(content, result)
        # L5: Requirements-to-import cross-check (REQ-SV-601)
        if sibling_imports:
            _validate_requirements_coverage(content, sibling_imports, result)
    elif name == "dockerfile" or name.startswith("dockerfile."):
        result = _validate_dockerfile(content, result)
    elif suffix in (".yaml", ".yml"):
        result = _validate_yaml_file(content, result)
    elif suffix == ".json":
        result = _validate_json_file(content, result)
    # HTML, Markdown, etc. — no validator, keep defaults (1.0)

    return result


def _validate_requirements_file(
    content: str,
    result: DiskComplianceResult,
) -> DiskComplianceResult:
    """Validate pip requirements format.

    Each non-empty, non-comment line must look like a valid package
    specifier: alphanumeric with hyphens/underscores/dots, optionally
    followed by extras or version constraints.  Lines like ``setCurrency``
    or ``browseProduct`` that are Python identifiers but not on PyPI are
    caught by checking for CamelCase or known non-package patterns.
    """
    # PEP 508 package name: letter/digit, hyphens, underscores, dots
    _PKG_RE = re.compile(
        r"^[A-Za-z0-9]([A-Za-z0-9._-]*[A-Za-z0-9])?(\[.*\])?\s*(~=|==|!=|>=|<=|>|<|===)?",
    )
    # Bare camelCase identifier with no version specifier — likely a function name
    _CAMEL_BARE_RE = re.compile(r"^[a-z]+[A-Z][a-zA-Z]*$")

    issues: list = []
    lines = [
        line.strip() for line in content.splitlines()
        if line.strip() and not line.strip().startswith("#")
        and not line.strip().startswith("-")  # pip flags like -e, --index-url
    ]

    for line in lines:
        # Strip inline comments
        spec = line.split("#")[0].strip()
        if not spec:
            continue
        if _CAMEL_BARE_RE.match(spec):
            issues.append(f"camelCase identifier (not a package): {spec}")
        elif not _PKG_RE.match(spec):
            issues.append(f"invalid package specifier: {spec}")

    if issues:
        # Scale contract_compliance by fraction of valid lines
        valid_count = len(lines) - len(issues)
        result.contract_compliance = max(0.0, valid_count / len(lines)) if lines else 0.0
        result.semantic_issues.extend(issues)
        result.error = f"{len(issues)} invalid package specifier(s)"

    return result


def _digest_looks_fabricated(digest: str) -> bool:
    """Heuristic: detect fabricated SHA256 digests (REQ-SV2-100).

    Real SHA256 digests have high Shannon entropy (~3.9 bits/char).
    LLM-fabricated digests often contain sequential hex nybble patterns
    or low-entropy repeated characters.
    """
    from math import log2

    d = digest.lower()
    length = len(d)
    if length == 0:
        return True

    # 1. Shannon entropy — real digests average ~3.9 bits/char
    freq: dict[str, int] = {}
    for c in d:
        freq[c] = freq.get(c, 0) + 1
    entropy = -sum((n / length) * log2(n / length) for n in freq.values())
    if entropy < 3.0:
        return True

    # 2. Nybble-level sequential detection — LLMs produce digests like
    #    "0d1e2f3a4b5c6d7e" where even-position hex chars count 0,1,2,...
    #    Check both even and odd nybble positions for runs of 8+ with
    #    constant diff (mod 16).
    nybbles = [int(c, 16) for c in d]
    for offset in (0, 1):
        stripe = nybbles[offset::2]
        if len(stripe) < 3:
            continue
        prev_diff = (stripe[1] - stripe[0]) % 16
        run = 2
        for i in range(2, len(stripe)):
            cur_diff = (stripe[i] - stripe[i - 1]) % 16
            if cur_diff == prev_diff:
                run += 1
                if run >= 8:
                    return True
            else:
                prev_diff = cur_diff
                run = 2

    return False


def _validate_dockerfile(
    content: str,
    result: DiskComplianceResult,
) -> DiskComplianceResult:
    """Validate that a Dockerfile has required directives and valid digests."""
    lines = content.splitlines()
    directives_found: set[str] = set()
    for lineno, line in enumerate(lines, 1):
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            match = re.match(r"^([A-Z]+)\s", stripped)
            if match:
                directives_found.add(match.group(1))

        # L3: SHA256 digest validation (REQ-SV-401)
        # L3+: Digest plausibility (REQ-SV2-100)
        if stripped.upper().startswith("FROM"):
            for digest_match in re.findall(r"@sha256:([0-9a-fA-F]*)", stripped):
                if len(digest_match) != 64:
                    result.semantic_issues.append({
                        "category": "dockerfile_digest",
                        "severity": "error",
                        "message": (
                            f"Truncated SHA256 digest: {len(digest_match)} chars "
                            f"(expected 64)"
                        ),
                        "line": lineno,
                        "symbol": (
                            f"sha256:{digest_match[:16]}..."
                            if digest_match
                            else "sha256:<empty>"
                        ),
                    })
                elif _digest_looks_fabricated(digest_match):
                    result.semantic_issues.append({
                        "category": "dockerfile_digest_fabricated",
                        "severity": "error",
                        "message": (
                            "SHA256 digest appears fabricated "
                            "(low entropy or sequential pattern)"
                        ),
                        "line": lineno,
                        "symbol": f"sha256:{digest_match[:16]}...",
                    })

    required = {"FROM"}
    # A valid Dockerfile needs at least FROM
    missing = required - directives_found
    if missing:
        result.ast_valid = False
        result.error = f"missing Dockerfile directive(s): {', '.join(sorted(missing))}"
        result.contract_compliance = 0.0
    elif not (directives_found & {"CMD", "ENTRYPOINT"}):
        # Warning: no entrypoint defined
        result.semantic_issues.append("no CMD or ENTRYPOINT directive")
        result.contract_compliance = 0.8

    return result


def _validate_yaml_file(
    content: str,
    result: DiskComplianceResult,
) -> DiskComplianceResult:
    """Validate YAML syntax."""
    try:
        import yaml
        yaml.safe_load(content)
    except ImportError:
        pass  # PyYAML not installed — skip
    except yaml.YAMLError as exc:
        result.ast_valid = False
        result.error = f"yaml_error: {exc}"
        result.contract_compliance = 0.0
    return result


def _validate_json_file(
    content: str,
    result: DiskComplianceResult,
) -> DiskComplianceResult:
    """Validate JSON syntax."""
    import json as _json
    try:
        _json.loads(content)
    except _json.JSONDecodeError as exc:
        result.ast_valid = False
        result.error = f"json_error: {exc}"
        result.contract_compliance = 0.0
    return result


def _count_stubs(tree: ast.AST) -> int:
    """Count stub bodies (raise NotImplementedError or bare pass) in functions."""
    count = 0
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            body = node.body
            # Strip leading docstring
            if (
                body
                and isinstance(body[0], ast.Expr)
                and isinstance(body[0].value, (ast.Constant, ast.Str))
            ):
                body = body[1:]
            if len(body) == 1:
                stmt = body[0]
                # bare pass
                if isinstance(stmt, ast.Pass):
                    count += 1
                # raise NotImplementedError
                elif isinstance(stmt, ast.Raise) and stmt.exc is not None:
                    if isinstance(stmt.exc, ast.Call):
                        func = stmt.exc.func
                        if isinstance(func, ast.Name) and func.id == "NotImplementedError":
                            count += 1
                    elif isinstance(stmt.exc, ast.Name) and stmt.exc.id == "NotImplementedError":
                        count += 1
    return count


def _count_duplicate_definitions(tree: ast.AST) -> int:
    """Count duplicate function/class names at module level only."""
    names: List[str] = []
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            names.append(node.name)
    seen: set = set()
    dupes = 0
    for name in names:
        if name in seen:
            dupes += 1
        seen.add(name)
    return dupes


def _detect_cross_scope_duplicates(tree: ast.AST) -> List[Dict[str, object]]:
    """Detect function/class names duplicated across scopes (REQ-SV-301).

    Returns semantic-issue dicts for names that appear at both module level
    and inside a nested scope (function body, class body).  This catches
    accidental copy-paste where a helper is defined inside a function AND
    duplicated at module level (e.g. ``talkToGemini`` in run-050).
    """
    # Module-level definitions: name → line
    module_names: Dict[str, int] = {}
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            module_names[node.name] = node.lineno

    # Walk nested scopes inside each top-level definition
    nested_hits: List[tuple] = []  # (name, nested_line, parent_name)
    for top_node in ast.iter_child_nodes(tree):
        if not isinstance(top_node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            continue
        for node in ast.walk(top_node):
            if node is top_node:
                continue
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                if node.name in module_names:
                    nested_hits.append(
                        (node.name, node.lineno, top_node.name)
                    )

    issues: List[Dict[str, object]] = []
    for name, nested_line, parent_name in nested_hits:
        issues.append({
            "category": "cross_scope_duplicate",
            "severity": "warning",
            "message": (
                f"'{name}' defined at module level (line {module_names[name]}) "
                f"and inside '{parent_name}' (line {nested_line})"
            ),
            "line": nested_line,
            "symbol": name,
        })
    return issues


_DEFAULT_FACTORY_PATTERNS = [
    re.compile(r"^create_"),
    re.compile(r"^make_"),
    re.compile(r"^build_"),
    re.compile(r"_factory$"),
]


def _validate_factory_returns(
    tree: ast.AST,
    *,
    patterns: Optional[List[str]] = None,
) -> List[Dict[str, object]]:
    """Check that factory functions return a value (REQ-SV-501).

    Flags ``create_*``, ``make_*``, ``build_*``, and ``*_factory``
    functions that have no ``return <expr>`` statement.
    """
    compiled = (
        [re.compile(p) for p in patterns]
        if patterns
        else _DEFAULT_FACTORY_PATTERNS
    )
    issues: List[Dict[str, object]] = []

    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if not any(p.search(node.name) for p in compiled):
            continue

        # Walk body for Return nodes with a non-None value
        has_value_return = False
        for child in ast.walk(node):
            if isinstance(child, ast.Return) and child.value is not None:
                has_value_return = True
                break

        if not has_value_return:
            issues.append({
                "category": "factory_return",
                "severity": "error",
                "message": (
                    f"Factory function '{node.name}' has no return "
                    f"statement with a value"
                ),
                "line": node.lineno,
                "symbol": node.name,
            })

    return issues


_KNOWN_NON_IMPORT_PACKAGES = frozenset({
    "setuptools", "wheel", "pip", "gunicorn", "uvicorn", "gevent",
    "pytest", "pytest-asyncio", "pytest-cov", "black", "ruff", "mypy",
})


def _validate_requirements_coverage(
    requirements_content: str,
    sibling_imports: Dict[str, Set[str]],
    result: DiskComplianceResult,
) -> None:
    """Check that every package in requirements.in is imported (REQ-SV-601).

    Appends ``orphan_dependency`` warnings to *result.semantic_issues*
    for packages that no sibling Python file imports.
    """
    from startd8.implementation_engine.package_aliases import pypi_to_import

    all_imports: Set[str] = set()
    for imports in sibling_imports.values():
        all_imports |= imports

    for lineno, line in enumerate(requirements_content.splitlines(), 1):
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith("-"):
            continue

        # Extract package name (before version specifier)
        spec = stripped.split("#")[0].strip()
        package = re.split(r"[~=!<>\[;]", spec)[0].strip().lower()
        if not package or package in _KNOWN_NON_IMPORT_PACKAGES:
            continue

        # Map package to expected import name
        expected_import = pypi_to_import(package)

        # Check if any sibling imports this package
        found = any(
            imp == expected_import
            or imp.startswith(expected_import + ".")
            or imp == package  # simple case: flask → flask
            or imp.startswith(package + ".")
            # REQ-SV2-300: reverse prefix — `from google.cloud import secretmanager`
            # produces imp="google.cloud", expected="google.cloud.secretmanager"
            or expected_import.startswith(imp + ".")
            for imp in all_imports
        )
        if not found:
            result.semantic_issues.append({
                "category": "orphan_dependency",
                "severity": "warning",
                "message": (
                    f"Package '{package}' in requirements.in is not "
                    f"imported by any sibling Python file"
                ),
                "line": lineno,
                "symbol": package,
            })


# Pure functions whose return value should not be discarded.
# Only includes functions detectable via AST callee extraction —
# i.e. the module/object name appears literally in the source code.
# Instance method calls like d.get() or s.replace() use the variable
# name, not the type name, so dict.get / str.replace are NOT included.
_PURE_FUNCTIONS = frozenset({
    "os.getenv",
    "os.environ.get",
    "os.path.join",
    "os.path.exists",
    "os.path.dirname",
    "os.path.basename",
    "os.path.abspath",
    "os.path.expanduser",
})


def _validate_discarded_returns(tree: ast.AST) -> List[Dict[str, object]]:
    """Flag expression statements that discard return values (REQ-SV-701).

    Only flags calls to functions in ``_PURE_FUNCTIONS`` — these are
    functions whose sole purpose is to return a value.  Side-effect
    calls like ``print()``, ``list.append()``, and ``logging.*`` are
    never flagged.
    """
    issues: List[Dict[str, object]] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Expr):
            continue
        if not isinstance(node.value, ast.Call):
            continue

        callee = _extract_callee_name(node.value)
        if callee and callee in _PURE_FUNCTIONS:
            issues.append({
                "category": "discarded_return",
                "severity": "warning",
                "message": f"Return value of '{callee}' is discarded",
                "line": node.lineno,
                "symbol": callee,
            })
    return issues


def _extract_callee_name(call_node: ast.Call) -> Optional[str]:
    """Extract dotted name from a Call node (e.g. ``os.getenv``)."""
    func = call_node.func
    if isinstance(func, ast.Name):
        return func.id
    if isinstance(func, ast.Attribute):
        parts: List[str] = []
        node: Any = func
        while isinstance(node, ast.Attribute):
            parts.append(node.attr)
            node = node.value
        if isinstance(node, ast.Name):
            parts.append(node.id)
            return ".".join(reversed(parts))
    return None


def _validate_service_identity(
    tree: ast.AST,
    file_path: str,
    sibling_files: Optional[List[str]] = None,
) -> List[Dict[str, object]]:
    """Flag logger calls with a different service's name (REQ-SV2-400).

    Detects copy-paste bugs where ``logger.py`` is duplicated across
    services but the component/service name string is not updated.
    """
    issues: List[Dict[str, object]] = []
    parts = Path(file_path).parts
    if len(parts) < 2:
        return issues
    expected_service = parts[-2].lower()

    # Build set of other service directory names from siblings
    other_services: set[str] = set()
    for sib in sibling_files or []:
        sib_parts = Path(sib).parts
        if len(sib_parts) >= 2:
            other_services.add(sib_parts[-2].lower())
    other_services.discard(expected_service)
    if not other_services:
        return issues

    _LOGGER_CALLEES = {"getlogger", "getjsonlogger", "get_logger", "basicconfig"}
    _IDENTITY_KWARGS = {"component", "service", "name"}
    _IDENTITY_PARAMS = {"component", "service", "name"}

    def _check_string(value: str, lineno: int, context: str) -> None:
        found = value.lower()
        for other in other_services:
            if other in found and expected_service not in found:
                issues.append({
                    "category": "service_identity_mismatch",
                    "severity": "error",
                    "message": (
                        f"{context} contains '{other}' "
                        f"but file is in '{expected_service}/' directory"
                    ),
                    "line": lineno,
                    "symbol": value,
                })
                break

    for node in ast.walk(tree):
        # Check function/method default parameter values:
        # def getJSONLogger(name='emailservice') or
        # def __init__(self, component='emailservice')
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            func_lower = node.name.lower()
            # Only check logger-related functions or identity params
            for arg, default in zip(
                reversed(node.args.args), reversed(node.args.defaults)
            ):
                param_name = arg.arg.lower()
                if (
                    isinstance(default, ast.Constant)
                    and isinstance(default.value, str)
                    and (param_name in _IDENTITY_PARAMS or func_lower in _LOGGER_CALLEES)
                ):
                    _check_string(
                        default.value, node.lineno,
                        f"Default for '{arg.arg}' in '{node.name}()'",
                    )
            continue

        if not isinstance(node, ast.Call):
            continue
        callee = _extract_callee_name(node)
        callee_tail = (callee or "").lower().split(".")[-1] if callee else ""

        # Check positional arg on logger factory calls
        if callee_tail in _LOGGER_CALLEES and node.args:
            arg = node.args[0]
            if isinstance(arg, ast.Constant) and isinstance(arg.value, str):
                _check_string(
                    arg.value, node.lineno,
                    f"Logger initialized with '{arg.value}'",
                )

        # Check identity keyword args on any call
        for kw in node.keywords:
            if kw.arg not in _IDENTITY_KWARGS:
                continue
            if isinstance(kw.value, ast.Constant) and isinstance(kw.value.value, str):
                _check_string(
                    kw.value.value, node.lineno,
                    f"Keyword '{kw.arg}'",
                )

    return issues


def _validate_method_resolution(tree: ast.AST) -> List[Dict[str, object]]:
    """Flag self.x() where x is a module-level function, not a method (REQ-SV2-500).

    Catches the recurring ``self.index()`` vs ``index(self)`` pattern
    in Locust TaskSets and similar frameworks.
    """
    issues: List[Dict[str, object]] = []

    # Pass 1: module-level function names
    module_funcs: set[str] = set()
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            module_funcs.add(node.name)

    if not module_funcs:
        return issues

    # Pass 2: per-class check
    for node in ast.iter_child_nodes(tree):
        if not isinstance(node, ast.ClassDef):
            continue
        class_methods: set[str] = set()
        for item in ast.iter_child_nodes(node):
            if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)):
                class_methods.add(item.name)

        for child in ast.walk(node):
            if (
                isinstance(child, ast.Attribute)
                and isinstance(child.value, ast.Name)
                and child.value.id == "self"
                and child.attr in module_funcs
                and child.attr not in class_methods
            ):
                issues.append({
                    "category": "method_resolution",
                    "severity": "warning",
                    "message": (
                        f"'self.{child.attr}()' called but '{child.attr}' "
                        f"is a module-level function, not a method of "
                        f"'{node.name}'"
                    ),
                    "line": child.lineno,
                    "symbol": child.attr,
                })

    return issues


def _validate_reachability(tree: ast.AST) -> List[Dict[str, object]]:
    """Flag module-level functions never referenced within the file (REQ-SV2-600).

    Only flags public (non-underscore) functions that are not ``main``,
    not in ``__all__``, and not referenced by any ``ast.Name`` load or
    dict/list/set literal in the same module.
    """
    issues: List[Dict[str, object]] = []

    # Collect module-level function defs (skip private, main, class methods)
    func_defs: dict[str, int] = {}
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if node.name.startswith("_") or node.name == "main":
                continue
            func_defs[node.name] = node.lineno

    if not func_defs:
        return issues

    # Collect all Name-load references (function calls, dict values, etc.)
    referenced: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Load):
            referenced.add(node.id)

    # Check __all__ exports
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "__all__":
                    if isinstance(node.value, (ast.List, ast.Tuple)):
                        for elt in node.value.elts:
                            if isinstance(elt, ast.Constant) and isinstance(elt.value, str):
                                referenced.add(elt.value)

    # A function defined at module level is "referenced" if its name
    # appears as a Name(Load) ANYWHERE in the file (including as a dict
    # key, decorator argument, list element, or function call).  The
    # definition itself uses Name(Store), so it won't false-match.
    for name, lineno in func_defs.items():
        if name not in referenced:
            issues.append({
                "category": "unreachable_function",
                "severity": "warning",
                "message": (
                    f"Module-level function '{name}' is defined "
                    f"but never called within the file"
                ),
                "line": lineno,
                "symbol": name,
            })

    return issues


def _emit_semantic_observability(
    result: "DiskComplianceResult",
    file_path: str,
    import_map: Optional[Dict[str, str]],
) -> None:
    """Log semantic issues and set OTel span attributes (REQ-SV-901/902)."""
    # Loki logging (REQ-SV-902)
    for issue in result.semantic_issues:
        if isinstance(issue, dict):
            logger.warning(
                "Semantic issue: %s",
                issue.get("message", str(issue)),
                extra={
                    "category": issue.get("category", "unknown"),
                    "severity": issue.get("severity", "unknown"),
                    "file_path": file_path,
                    "line": issue.get("line"),
                },
            )

    # OTel span attributes (REQ-SV-901)
    try:
        from opentelemetry import trace

        span = trace.get_current_span()
        if span.is_recording():
            error_count = 0
            warning_count = 0
            categories: Set[str] = set()
            for i in result.semantic_issues:
                if isinstance(i, dict):
                    sev = i.get("severity")
                    if sev == "error":
                        error_count += 1
                    elif sev == "warning":
                        warning_count += 1
                    cat = i.get("category")
                    if cat:
                        categories.add(cat)
            span.set_attribute(
                "semantic_validation.issues_count",
                len(result.semantic_issues),
            )
            span.set_attribute("semantic_validation.error_count", error_count)
            span.set_attribute("semantic_validation.warning_count", warning_count)
            if categories:
                span.set_attribute(
                    "semantic_validation.categories", sorted(categories),
                )
            span.set_attribute(
                "semantic_validation.import_map_mode",
                import_map is not None,
            )
    except Exception as exc:
        logger.debug("OTel span attributes skipped: %s", exc)


def _validate_import_resolution(
    tree: ast.AST,
    file_path: str,
    project_root: str,
    *,
    sibling_files: Optional[List[str]] = None,
    import_map: Optional[Dict[str, str]] = None,
) -> List[Dict[str, object]]:
    """Validate that all imports resolve to known sources (REQ-SV-201).

    Returns a list of structured semantic-issue dicts for unresolvable
    imports.  Each dict has ``category``, ``severity``, ``message``,
    ``line``, and ``symbol`` keys.
    """
    from startd8.utils.import_resolution import (
        extract_import_modules,
        discover_sibling_modules,
        resolve_import,
        parse_requirements_packages,
    )

    issues: List[Dict[str, object]] = []

    # Build sibling module set
    if sibling_files is not None:
        sibling_modules: Set[str] = set()
        for f in sibling_files:
            p = Path(f)
            sibling_modules.add(p.stem)
            if p.parent.name:
                sibling_modules.add(p.parent.name)
    else:
        sibling_modules = discover_sibling_modules(file_path, project_root)

    # Build requirements package set from sibling requirements.in
    requirements_packages = _discover_requirements_packages(
        file_path, project_root,
    )

    # Build set of proto stubs that actually exist as sibling files.
    # When sibling_files is available, _pb2 imports are verified against it.
    # This catches hallucinated proto names like email_service_pb2 when the
    # actual proto stub is demo_pb2.  (Run-055 F-2)
    known_proto_stems: Optional[Set[str]] = None
    if sibling_files is not None:
        known_proto_stems = set()
        from startd8.utils.requirements_generator import _PROTOBUF_STUB_RE
        for f in sibling_files:
            stem = Path(f).stem
            if _PROTOBUF_STUB_RE.match(stem):
                known_proto_stems.add(stem)

    # Resolve each import — try full dotted path first (catches google.api_core
    # via alias prefix matching), then fall back to top-level module name.
    for imp in extract_import_modules(tree):
        module_name = str(imp["module"])
        full_path = str(imp["full_path"])
        line = imp["line"]

        resolution = resolve_import(
            full_path,
            sibling_modules=sibling_modules,
            requirements_packages=requirements_packages,
            import_map=import_map,
        )
        if resolution is None and full_path != module_name:
            resolution = resolve_import(
                module_name,
                sibling_modules=sibling_modules,
                requirements_packages=requirements_packages,
                import_map=import_map,
            )

        # Proto stub verification: if the import resolved as "proto" but
        # we have a sibling file inventory and no matching _pb2.py exists,
        # downgrade to error.  (Run-055 F-2: email_service_pb2 accepted
        # by regex but actual proto is demo_pb2.)
        if (
            resolution is not None
            and resolution == "proto"
            and known_proto_stems is not None
            and module_name not in known_proto_stems
        ):
            issues.append({
                "category": "import_resolution",
                "severity": "error",
                "message": (
                    f"Proto stub '{module_name}' not found among sibling files. "
                    f"Known proto stubs: {sorted(known_proto_stems) or '(none)'}"
                ),
                "line": line,
                "symbol": full_path,
            })
            continue

        if resolution is None:
            issues.append({
                "category": "import_resolution",
                "severity": "error",
                "message": (
                    f"Unresolvable import: '{full_path}' is not stdlib, "
                    f"not in requirements.in, not a local module, "
                    f"and not a protobuf stub"
                ),
                "line": line,
                "symbol": full_path,
            })

    return issues


def _discover_requirements_packages(
    file_path: str, project_root: str,
) -> Set[str]:
    """Find ``requirements.in`` in the same directory and extract package names."""
    from startd8.utils.import_resolution import parse_requirements_packages

    abs_path = Path(project_root) / file_path
    parent = abs_path.parent

    for name in ("requirements.in", "requirements.txt"):
        req_file = parent / name
        if req_file.is_file():
            try:
                content = req_file.read_text(encoding="utf-8", errors="replace")
                return parse_requirements_packages(content)
            except OSError:
                pass
    return set()


def _extract_import_modules(tree: ast.AST) -> List[str]:
    """Extract all imported module names from an AST."""
    modules: List[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                modules.append(alias.name)
        elif isinstance(node, ast.ImportFrom):
            if node.module:
                modules.append(node.module)
    return modules


def _validate_disk_file_against_spec(
    tree: ast.AST,
    spec: ForwardFileSpec,
    file_path: str,
) -> List[ContractViolation]:
    """Check disk AST against forward manifest spec (simplified, no registry)."""
    violations: List[ContractViolation] = []

    # Check elements exist
    if spec.elements:
        actual_names: set = set()
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                actual_names.add(node.name)
        for expected_el in spec.elements:
            if expected_el.name not in actual_names:
                violations.append(ContractViolation(
                    contract_id=f"disk:{file_path}:{expected_el.name}",
                    violation_type=f"missing_{expected_el.kind.value}",
                    expected=f"Element `{expected_el.name}`",
                    actual="Not found on disk",
                    file_path=file_path,
                    severity="error",
                ))

    # Check imports
    if spec.imports:
        actual_imports = _extract_import_modules(tree)
        for req_imp in spec.imports:
            found = any(
                ai == req_imp.module or ai.startswith(req_imp.module + ".")
                for ai in actual_imports
            )
            if not found:
                violations.append(ContractViolation(
                    contract_id=f"disk_import:{file_path}:{req_imp.module}",
                    violation_type="missing_import",
                    expected=f"Import `{req_imp.module}`",
                    actual="Not found on disk",
                    file_path=file_path,
                    severity="error",
                ))

    return violations
