"""Tests for INTEGRATE phase merge reconciliation.

Verifies that files generated by IMPLEMENT but not merged by INTEGRATE
are detected and flagged in the integration results.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest

from startd8.contractors.protocols import GenerationResult


def _make_context(
    tmp_path: Path,
    generation_results: dict[str, GenerationResult],
    tasks: list[Any] | None = None,
) -> dict[str, Any]:
    """Build a minimal INTEGRATE context."""
    from tests.unit.contractors.conftest import FakeSeedTask

    if tasks is None:
        tasks = [FakeSeedTask(task_id=tid) for tid in generation_results]

    staging = tmp_path / "staging"
    staging.mkdir(exist_ok=True)

    # Write staging files so the integration engine can find them
    for tid, gr in generation_results.items():
        task_dir = staging / tid
        task_dir.mkdir(exist_ok=True)
        for f in gr.generated_files:
            staged = task_dir / f.name
            staged.write_text(f"# generated: {f.name}\n")

    return {
        "tasks": tasks,
        "task_index": {t.task_id: t for t in tasks},
        "generation_results": generation_results,
        "staging_dir": str(staging),
        "project_root": str(tmp_path / "project"),
        "dry_run": False,
    }


@pytest.mark.unit
class TestIntegrateReconciliation:
    """Test the post-merge reconciliation that detects missing files."""

    def test_missing_file_flagged(self, tmp_path):
        """When IMPLEMENT generates 2 files but only 1 is merged, flag the missing one."""
        project = tmp_path / "project"
        project.mkdir()

        file_a = Path("/staging/T-1/widget.py")
        file_b = Path("/staging/T-1/utils.py")

        gr = GenerationResult(
            success=True,
            generated_files=[file_a, file_b],
            cost_usd=0.05,
            model="mock:mock",
        )

        # Simulate integration results where only widget.py was merged
        integration_results = {
            "T-1": {
                "success": True,
                "integrated_files": [str(project / "widget.py")],
                "skipped_files": [],
            }
        }

        # Run the reconciliation logic directly
        generation_results = {"T-1": gr}
        _total_missing = 0
        for task_id, gen in generation_results.items():
            if not gen.success:
                continue
            ir = integration_results.get(task_id, {})
            if ir.get("status") == "BLOCKED":
                continue

            integrated = {Path(f).name for f in ir.get("integrated_files", [])}
            expected = {f.name for f in gen.generated_files}

            for sf in ir.get("skipped_files", []):
                if isinstance(sf, dict):
                    sp = sf.get("path", "")
                    if sp:
                        integrated.add(Path(sp).name)
                elif isinstance(sf, str):
                    integrated.add(Path(sf).name)

            missing = expected - integrated
            if missing:
                _total_missing += len(missing)
                ir["_missing_files"] = sorted(missing)

        assert _total_missing == 1
        assert integration_results["T-1"]["_missing_files"] == ["utils.py"]

    def test_all_files_merged_no_flag(self, tmp_path):
        """When all files are merged, no _missing_files key should appear."""
        project = tmp_path / "project"
        project.mkdir()

        file_a = Path("/staging/T-1/widget.py")
        file_b = Path("/staging/T-1/utils.py")

        gr = GenerationResult(
            success=True,
            generated_files=[file_a, file_b],
            cost_usd=0.05,
            model="mock:mock",
        )

        integration_results = {
            "T-1": {
                "success": True,
                "integrated_files": [
                    str(project / "widget.py"),
                    str(project / "utils.py"),
                ],
                "skipped_files": [],
            }
        }

        generation_results = {"T-1": gr}
        for task_id, gen in generation_results.items():
            if not gen.success:
                continue
            ir = integration_results.get(task_id, {})
            integrated = {Path(f).name for f in ir.get("integrated_files", [])}
            expected = {f.name for f in gen.generated_files}
            missing = expected - integrated
            if missing:
                ir["_missing_files"] = sorted(missing)

        assert "_missing_files" not in integration_results["T-1"]

    def test_skipped_files_counted_as_accounted(self, tmp_path):
        """Files in skipped_files should not be flagged as missing."""
        project = tmp_path / "project"
        project.mkdir()

        file_a = Path("/staging/T-1/widget.py")
        file_b = Path("/staging/T-1/big_file.py")

        gr = GenerationResult(
            success=True,
            generated_files=[file_a, file_b],
            cost_usd=0.05,
            model="mock:mock",
        )

        integration_results = {
            "T-1": {
                "success": True,
                "integrated_files": [str(project / "widget.py")],
                "skipped_files": [
                    {"path": str(project / "big_file.py"), "reason": "size_regression"}
                ],
            }
        }

        generation_results = {"T-1": gr}
        for task_id, gen in generation_results.items():
            if not gen.success:
                continue
            ir = integration_results.get(task_id, {})
            integrated = {Path(f).name for f in ir.get("integrated_files", [])}
            expected = {f.name for f in gen.generated_files}

            for sf in ir.get("skipped_files", []):
                if isinstance(sf, dict):
                    sp = sf.get("path", "")
                    if sp:
                        integrated.add(Path(sp).name)
                elif isinstance(sf, str):
                    integrated.add(Path(sf).name)

            missing = expected - integrated
            if missing:
                ir["_missing_files"] = sorted(missing)

        assert "_missing_files" not in integration_results["T-1"]

    def test_failed_generation_skipped(self, tmp_path):
        """Tasks with failed generation should be skipped during reconciliation."""
        gr = GenerationResult(
            success=False,
            generated_files=[],
            cost_usd=0.0,
            model="mock:mock",
            error="Generation failed",
        )

        integration_results = {"T-1": {"success": False}}
        generation_results = {"T-1": gr}
        _total_missing = 0

        for task_id, gen in generation_results.items():
            if not gen.success:
                continue
            ir = integration_results.get(task_id, {})
            integrated = {Path(f).name for f in ir.get("integrated_files", [])}
            expected = {f.name for f in gen.generated_files}
            missing = expected - integrated
            if missing:
                _total_missing += len(missing)
                ir["_missing_files"] = sorted(missing)

        assert _total_missing == 0
        assert "_missing_files" not in integration_results["T-1"]

    def test_blocked_task_skipped(self, tmp_path):
        """Tasks with BLOCKED status should be skipped during reconciliation."""
        file_a = Path("/staging/T-1/widget.py")

        gr = GenerationResult(
            success=True,
            generated_files=[file_a],
            cost_usd=0.05,
            model="mock:mock",
        )

        integration_results = {
            "T-1": {
                "success": False,
                "status": "BLOCKED",
                "integrated_files": [],
            }
        }

        generation_results = {"T-1": gr}
        _total_missing = 0

        for task_id, gen in generation_results.items():
            if not gen.success:
                continue
            ir = integration_results.get(task_id, {})
            if ir.get("status") == "BLOCKED":
                continue
            integrated = {Path(f).name for f in ir.get("integrated_files", [])}
            expected = {f.name for f in gen.generated_files}
            missing = expected - integrated
            if missing:
                _total_missing += len(missing)
                ir["_missing_files"] = sorted(missing)

        assert _total_missing == 0
        assert "_missing_files" not in integration_results["T-1"]
