// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/spec/go/dashboard

package dashboard

#AnnotationDisplay: {
	name:         string @go(Name)
	description?: string @go(Description)
	hidden?:      bool   @go(Hidden)
	color?:       string @go(Color)
}

#AnnotationSpec: _
