// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/spec/go/dashboard

package dashboard

import "github.com/perses/spec/cue/dashboard/variable"

_#variableSpec: _

#TextVariableSpec: _

#ListVariableSpec: _

#Variable: _

_#tmpVariable: {
	kind: variable.#Kind @go(Kind)
	spec: _              @go(Spec,any)
}
