#!/usr/bin/env python3
"""Analyze OTel Demo Python sources against the Python capability index.

Walks ``.otel-demo/src/**/*.py`` (or ``--workdir``), emits per-file hyp(f) reports,
and computes corpus coverage % across four index dimensions.

Usage:
    scripts/otel_demo/bring_up.sh --no-clone   # ensure .otel-demo clone exists
    python3 scripts/analyze_otel_demo_python_coverage.py

    python3 scripts/analyze_otel_demo_python_coverage.py \\
        --workdir /path/to/opentelemetry-demo \\
        --out docs/design/python-capability-index/otel-demo-python-coverage.json
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from scripts.python_capability_resolver import (  # noqa: E402
    analyze_corpus,
    report_to_dict,
)

DEFAULT_WORKDIR = REPO / ".otel-demo"
OUT_DIR = REPO / "docs" / "design" / "python-capability-index"


def _render_markdown(report_dict: dict) -> str:
    s = report_dict["summary"]
    dims = report_dict["dimensions"]
    lines = [
        "# OTel Demo — Python Capability Index Coverage",
        "",
        f"**Corpus:** `{report_dict['corpus']}`  ",
        f"**Workdir:** `{report_dict['workdir']}`  ",
        f"**Files analyzed:** {s['files_analyzed']} "
        f"(skipped generated: {s['files_skipped_generated']}, parse errors: {s['files_parse_error']})  ",
        f"**Overall index coverage:** **{s['overall_index_percent']}%** (mean of four dimensions)",
        "",
        "## Dimension breakdown",
        "",
        "| Dimension | Detected | Total | Coverage |",
        "| --- | ---: | ---: | ---: |",
    ]
    for d in dims:
        lines.append(
            f"| {d['dimension']} | {d['detected_count']} | {d['total']} | {d['percent']}% |"
        )

    lines.extend(
        [
            "",
            "## OTel §5 patterns detected (union)",
            "",
        ]
    )
    if s["pattern_union"]:
        for pid in s["pattern_union"]:
            lines.append(f"- `{pid}`")
    else:
        lines.append("- *(none)*")

    lines.extend(["", "## Patterns not evidenced in Python sources", ""])
    if s["pattern_missing"]:
        for pid in s["pattern_missing"]:
            lines.append(f"- `{pid}`")
    else:
        lines.append("- *(full pattern coverage)*")

    lines.extend(["", "## Per-file hyp(f)", ""])
    for f in report_dict["files"]:
        if f.get("skipped_generated"):
            lines.append(f"- `{f['rel_path']}` — *skipped (generated protobuf)*")
            continue
        if f.get("parse_error"):
            lines.append(f"- `{f['rel_path']}` — **parse error:** {f['parse_error']}")
            continue
        hyp = ", ".join(f["hyp"]) if f["hyp"] else "∅"
        kinds = ", ".join(f.get("manifest_kinds") or []) or "—"
        lines.append(f"- `{f['rel_path']}` ({f['lines']} lines) — **hyp:** {hyp}; manifest: {kinds}")

    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- **communication_patterns** — share of `PY-OTEL-5.*` crosswalk entries with static "
            "import/call/decorator evidence (landscape §5).",
            "- **ast_nodes** — share of catalogued `PY-AST-*` node types appearing anywhere in the corpus.",
            "- **language_composites** — share of `PY-LC-*` composites evidenced.",
            "- **manifest_kinds** — share of `PY-MAN-*` ElementKind values extractable from AST.",
            "",
            "Generated by `scripts/analyze_otel_demo_python_coverage.py`.",
            "",
        ]
    )
    return "\n".join(lines)


def _resolve_workdir(explicit: Path | None) -> Path:
    if explicit is not None:
        return explicit.resolve()
    if (DEFAULT_WORKDIR / "src").is_dir():
        return DEFAULT_WORKDIR.resolve()
    fallback = Path("/tmp/otel-demo-proto-fetch")
    if (fallback / "src").is_dir():
        return fallback.resolve()
    raise SystemExit(
        "ERROR: no OTel Demo tree found. Run scripts/otel_demo/bring_up.sh or pass --workdir."
    )


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--workdir", type=Path, default=None, help="OTel Demo clone root")
    ap.add_argument("--include-generated", action="store_true", help="Include *_pb2*.py files")
    ap.add_argument(
        "--out",
        type=Path,
        default=OUT_DIR / "otel-demo-python-coverage.json",
    )
    ap.add_argument("--md-out", type=Path, default=OUT_DIR / "otel-demo-python-coverage.md")
    args = ap.parse_args(argv)

    workdir = _resolve_workdir(args.workdir)
    report = analyze_corpus(
        workdir,
        corpus="otel-demo-python",
        skip_generated=not args.include_generated,
    )
    doc = report_to_dict(report)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        json.dump(doc, fh, indent=2, sort_keys=True)
        fh.write("\n")

    md = _render_markdown(doc)
    args.md_out.write_text(md, encoding="utf-8")

    s = doc["summary"]
    print(f"wrote {args.out}")
    print(f"wrote {args.md_out}")
    print(f"overall index coverage: {s['overall_index_percent']}%")
    for d in doc["dimensions"]:
        print(f"  {d['dimension']}: {d['percent']}% ({d['detected_count']}/{d['total']})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
