"""Theme partials for the `{% import %}` seam (FR-12 component macros, FR-13 shell/IA).

``backend_codegen``'s ``base.html`` carries three *tolerant* hooks — ``{% include "theme/_head_extra.html"
ignore missing %}``, ``theme/_header.html``, ``theme/_footer.html`` — that are no-ops until polish drops
the partials into ``app/templates/theme/``. This module renders those partials. The header/footer
``{% import %}`` a shared macro library (``theme/_components.html``: ``badge``, ``card``, ``brand_header``,
``site_footer``) — that import is the seam this slice unlocks.

The partials are **theme-independent markup** carrying semantic classes; the per-theme *look* comes from
the already-themed stylesheet (``css.py`` styles ``.app-header`` / ``.app-footer`` / ``.brand`` / ``.badge``
/ ``.card`` via the same tokens). So they are constant + deterministic, and every theme reuses them.

All four files carry the ``STARTD8-POLISH`` marker (inside a Jinja ``{# … #}`` comment) so the provider
owns them and re-render+compare decides in-sync-ness — exactly like the stylesheet.
"""

from __future__ import annotations

from .css import POLISH_MARKER, POLISH_VERSION

_MARK = f"{{# {POLISH_MARKER} v{POLISH_VERSION} — generated by `startd8 polish`; regenerated on re-run #}}\n"


def render_components_macros() -> str:
    """``theme/_components.html`` — the importable Jinja macro library (the seam's payload)."""
    return (
        _MARK
        + '{# Reusable presentation macros. Import with: {% import "theme/_components.html" as ui %} #}\n'
        "{% macro badge(text, kind='') %}<span class=\"badge{% if kind %} badge--{{ kind }}{% endif %}\">"
        "{{ text }}</span>{% endmacro %}\n"
        "{% macro card(title='') %}<section class=\"card\">"
        '{% if title %}<h3 class="card__title">{{ title }}</h3>{% endif %}'
        '<div class="card__body">{{ caller() }}</div></section>{% endmacro %}\n'
        # Context-free: usable from an included partial (no `self`/block access). `label` defaults to
        # a neutral placeholder — the real brand is the company's to set (bucket 4).
        "{% macro brand_header(label='Home') %}"
        '<a class="skip-link sr-only" href="#main-content">Skip to main content</a>'
        '<header class="app-header"><a class="brand" href="/">{{ label }}</a></header>'
        "{% endmacro %}\n"
        "{% macro site_footer(text) %}"
        '<footer class="app-footer"><small>{{ text }}</small></footer>'
        "{% endmacro %}\n"
    )


def render_header_partial() -> str:
    """``theme/_header.html`` — a skip-link + branded header bar, via ``brand_header`` (the import seam)."""
    return (
        _MARK
        + '{% import "theme/_components.html" as ui %}\n'
        + "{{ ui.brand_header() }}\n"
    )


def render_footer_partial() -> str:
    """``theme/_footer.html`` — a site footer, via the ``site_footer`` macro."""
    return (
        _MARK + '{% import "theme/_components.html" as ui %}\n'
        "{{ ui.site_footer('Built with startd8 — polished, accessible UI.') }}\n"
    )


def render_head_extra() -> str:
    """``theme/_head_extra.html`` — extra ``<head>`` markup (color-scheme hint; font hooks if ever needed)."""
    return _MARK + '<meta name="color-scheme" content="light">\n'
