"""Deterministic stylesheet + static-mount generators for Presentation Polish.

``render_stylesheet`` projects a :class:`ThemeTokens` into a complete, plain-CSS stylesheet that
restyles the **existing** semantic HTML emitted by ``backend_codegen`` (``<nav>``, ``<main>``,
``<table>``, ``.field``, ``.flash``, ``<button>``, links, headings) — no template-body edits
required. It also carries a WCAG 2.2 AA accessibility baseline in CSS: visible ``:focus-visible``
rings, ``prefers-reduced-motion`` safety, adequate target sizing, and a ``.sr-only`` utility.

Output is byte-stable for a given (theme, ``POLISH_VERSION``): the same inputs always produce the
same bytes, so polish is idempotent and the file's in-sync-ness is decidable by re-render + compare.

``render_static_setup`` emits the tiny ``app/static_setup.py`` module that mounts ``app/static`` —
the project-owned half of the FR-25 seam (``backend_codegen``'s ``main.py`` imports it tolerantly).
"""

from __future__ import annotations

from .tokens import ThemeTokens

# Substring stamped into every polish-owned artifact. The provider's ``owns()`` checks for it;
# it is comment-syntax-agnostic (lives inside ``/* */`` in CSS and ``#`` in Python).
POLISH_MARKER = "STARTD8-POLISH"

# Bump when the generator's output shape changes — invalidates idempotency / triggers re-render.
# v2: added component styles (.app-header/.app-footer/.brand/.badge/.card) for the theme-partial seam.
POLISH_VERSION = "2"


def _scale(base_rem: float, ratio: float, step: int) -> str:
    """Modular type-scale size at *step* (…-1, 0, 1, 2, 3…) as a rounded ``rem`` string."""
    return f"{round(base_rem * (ratio ** step), 3)}rem"


def render_stylesheet(theme: ThemeTokens) -> str:
    """The complete app stylesheet for *theme*. Deterministic; carries the polish marker header."""
    base = 1.0
    r = theme.scale_ratio
    h1 = _scale(base, r, 3)
    h2 = _scale(base, r, 2)
    h3 = _scale(base, r, 1)
    small = _scale(base, r, -1)

    header = (
        f"/* {POLISH_MARKER} v{POLISH_VERSION} theme={theme.name} */\n"
        f"/* Generated by `startd8 polish` — deterministic, $0. Do not edit: regenerated on re-run. */\n"
    )

    root = (
        ":root {\n"
        f"  --color-bg: {theme.bg};\n"
        f"  --color-surface: {theme.surface};\n"
        f"  --color-text: {theme.text};\n"
        f"  --color-muted: {theme.muted};\n"
        f"  --color-primary: {theme.primary};\n"
        f"  --color-on-primary: {theme.on_primary};\n"
        f"  --color-border: {theme.border};\n"
        f"  --color-success: {theme.success};\n"
        f"  --color-success-bg: {theme.success_bg};\n"
        f"  --color-danger: {theme.danger};\n"
        f"  --color-danger-bg: {theme.danger_bg};\n"
        f"  --color-focus: {theme.focus};\n"
        f"  --font-sans: {theme.font_sans};\n"
        f"  --font-serif: {theme.font_serif};\n"
        f"  --font-mono: {theme.font_mono};\n"
        f"  --font-heading: {theme.heading_font};\n"
        f"  --text-base: {theme.text_base};\n"
        f"  --text-h1: {h1};\n"
        f"  --text-h2: {h2};\n"
        f"  --text-h3: {h3};\n"
        f"  --text-small: {small};\n"
        f"  --space: {theme.space_unit};\n"
        f"  --radius: {theme.radius};\n"
        f"  --shadow: {theme.shadow};\n"
        f"  --max-width: {theme.max_width};\n"
        "}\n"
    )

    # Static rules use var(--…) so the cascade is fully token-driven. These target the EXISTING
    # markup from backend_codegen — nothing here assumes new template structure.
    rules = """
*, *::before, *::after { box-sizing: border-box; }
html { -webkit-text-size-adjust: 100%; }
body {
  margin: 0;
  font-family: var(--font-sans);
  font-size: var(--text-base);
  line-height: 1.6;
  color: var(--color-text);
  background: var(--color-bg);
}

main {
  max-width: var(--max-width);
  margin: 0 auto;
  padding: calc(var(--space) * 3) calc(var(--space) * 2);
}

/* Typography */
h1, h2, h3 { font-family: var(--font-heading); line-height: 1.2; margin: 0 0 var(--space); }
h1 { font-size: var(--text-h1); letter-spacing: -0.02em; }
h2 { font-size: var(--text-h2); }
h3 { font-size: var(--text-h3); }
p { margin: 0 0 var(--space); }
small, .text-small { font-size: var(--text-small); color: var(--color-muted); }

a { color: var(--color-primary); text-decoration: none; }
a:hover { text-decoration: underline; }

/* Navigation */
nav {
  background: var(--color-surface);
  border-bottom: 1px solid var(--color-border);
  padding: var(--space) calc(var(--space) * 2);
  display: flex;
  flex-wrap: wrap;
  gap: calc(var(--space) * 1.5);
  align-items: center;
}
nav a { margin-right: 0; color: var(--color-text); font-weight: 500; }
nav a:hover { color: var(--color-primary); text-decoration: none; }

/* Tables */
table {
  border-collapse: collapse;
  width: 100%;
  margin-top: var(--space);
  background: var(--color-bg);
  border: 1px solid var(--color-border);
  border-radius: var(--radius);
  overflow: hidden;
}
thead { background: var(--color-surface); }
th, td {
  border-bottom: 1px solid var(--color-border);
  padding: calc(var(--space) * 1.25) calc(var(--space) * 1.5);
  text-align: left;
  vertical-align: top;
}
th { font-weight: 600; color: var(--color-muted); font-size: var(--text-small); text-transform: uppercase; letter-spacing: 0.03em; }
tbody tr:last-child td { border-bottom: none; }
tbody tr:hover { background: var(--color-surface); }
tr.new-row td { background: var(--color-success-bg); }

/* Flash / status */
.flash {
  background: var(--color-success-bg);
  border: 1px solid var(--color-success);
  color: var(--color-success);
  padding: var(--space) calc(var(--space) * 1.5);
  border-radius: var(--radius);
  margin-bottom: calc(var(--space) * 2);
}

/* Forms */
.field { margin-bottom: calc(var(--space) * 2); }
.field label { display: block; font-weight: 600; margin-bottom: calc(var(--space) * 0.5); }
.field-error { color: var(--color-danger); font-size: var(--text-small); display: block; margin-top: calc(var(--space) * 0.5); }
input, select, textarea {
  font: inherit;
  width: 100%;
  max-width: 28rem;
  padding: calc(var(--space) * 1.1) calc(var(--space) * 1.25);
  color: var(--color-text);
  background: var(--color-bg);
  border: 1px solid var(--color-border);
  border-radius: var(--radius);
}
input:focus, select:focus, textarea:focus { border-color: var(--color-primary); }

/* Buttons & primary actions */
button, .btn {
  font: inherit;
  font-weight: 600;
  cursor: pointer;
  min-height: 2.5rem;           /* WCAG 2.2 target size */
  padding: calc(var(--space) * 1.1) calc(var(--space) * 2);
  color: var(--color-on-primary);
  background: var(--color-primary);
  border: 1px solid var(--color-primary);
  border-radius: var(--radius);
  box-shadow: var(--shadow);
}
button:hover, .btn:hover { filter: brightness(0.94); }

/* Components (consumed by the theme partials' macros — theme/_components.html) */
.app-header {
  background: var(--color-surface);
  border-bottom: 1px solid var(--color-border);
  padding: calc(var(--space) * 1.5) calc(var(--space) * 2);
}
.app-header .brand, .brand {
  font-family: var(--font-heading);
  font-size: var(--text-h3);
  font-weight: 700;
  color: var(--color-text);
  text-decoration: none;
  letter-spacing: -0.01em;
}
.app-footer {
  border-top: 1px solid var(--color-border);
  padding: calc(var(--space) * 2);
  margin-top: calc(var(--space) * 4);
  color: var(--color-muted);
  text-align: center;
}
.badge {
  display: inline-block;
  padding: calc(var(--space) * 0.25) calc(var(--space) * 0.9);
  font-size: var(--text-small);
  font-weight: 600;
  border-radius: 999px;
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  color: var(--color-muted);
}
.badge--success { background: var(--color-success-bg); border-color: var(--color-success); color: var(--color-success); }
.badge--danger { background: var(--color-danger-bg); border-color: var(--color-danger); color: var(--color-danger); }
.card {
  background: var(--color-bg);
  border: 1px solid var(--color-border);
  border-radius: var(--radius);
  box-shadow: var(--shadow);
  padding: calc(var(--space) * 2);
  margin-bottom: calc(var(--space) * 2);
}
.card__title { margin-top: 0; }

/* Accessibility baseline (WCAG 2.2 AA) */
:focus-visible {
  outline: 3px solid var(--color-focus);
  outline-offset: 2px;
  border-radius: var(--radius);
}
.sr-only {
  position: absolute; width: 1px; height: 1px;
  padding: 0; margin: -1px; overflow: hidden;
  clip: rect(0, 0, 0, 0); white-space: nowrap; border: 0;
}
/* Skip-link: visually hidden until focused, then revealed (keyboard a11y). */
.skip-link:focus {
  position: fixed; top: var(--space); left: var(--space);
  width: auto; height: auto; margin: 0; overflow: visible; clip: auto;
  z-index: 1000; padding: calc(var(--space) * 0.75) calc(var(--space) * 1.25);
  background: var(--color-primary); color: var(--color-on-primary);
  border-radius: var(--radius); box-shadow: var(--shadow);
}
main:focus { outline: none; }
@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }
}

/* Responsive: stack tables on narrow viewports without losing semantics */
@media (max-width: 38rem) {
  main { padding: calc(var(--space) * 2) var(--space); }
  nav { gap: var(--space); }
  table, thead, tbody, th, td, tr { display: block; }
  thead { position: absolute; left: -9999px; }   /* visually hide header; cells label themselves below */
  tbody tr { border: 1px solid var(--color-border); border-radius: var(--radius); margin-bottom: var(--space); padding: var(--space); }
  td { border: none; padding: calc(var(--space) * 0.5) 0; }
}
"""
    return header + "\n" + root + rules


def render_static_setup() -> str:
    """The project-owned ``app/static_setup.py`` that mounts ``app/static`` at ``/static``.

    ``backend_codegen``'s ``main.py`` imports ``mount_static`` tolerantly (no-op when this module is
    absent), so it survives ``generate backend`` and the mount activates only once polish has run.
    """
    return (
        f"# {POLISH_MARKER} v{POLISH_VERSION}\n"
        '"""Static-asset mount for `startd8 polish` — owned by polish, imported tolerantly by main.py.\n\n'
        "Regenerated on `startd8 polish` re-run; safe to leave in place. Mounts app/static at /static\n"
        'so the polished stylesheet at /static/css/app.css resolves."""\n'
        "from __future__ import annotations\n\n"
        "from pathlib import Path\n\n"
        "from fastapi import FastAPI\n"
        "from fastapi.staticfiles import StaticFiles\n\n"
        '_STATIC_DIR = Path(__file__).resolve().parent / "static"\n\n\n'
        "def mount_static(app: FastAPI) -> None:\n"
        '    """Mount app/static at /static if the directory exists (it does once polish has run)."""\n'
        "    if _STATIC_DIR.is_dir():\n"
        '        app.mount("/static", StaticFiles(directory=str(_STATIC_DIR)), name="static")\n'
    )
