// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/spec/go/dashboard/variable

package variable

#Kind: _ // #enumKind

#enumKind:
	#KindText |
	#KindList

#KindText: #Kind & "TextVariable"
#KindList: #Kind & "ListVariable"

#Display: {
	name?:        string @go(Name)
	description?: string @go(Description)
	hidden:       bool   @go(Hidden)
}
