/**
 * lib/value-model.ts
 *
 * Single canonical Zod schema definitions mirroring all Prisma Value Model
 * entities. These schemas are the shared contract between API routes, server
 * actions, and client components.
 *
 * Field mapping conventions:
 *   - Prisma String   → z.string()
 *   - Prisma String?  → z.string().nullable()
 *   - Prisma DateTime → z.string().datetime()  (ISO-8601 wire format)
 *   - Prisma Json     → z.unknown()
 *   - @default fields → .optional() (server-generated, not required on input)
 *   - @id fields      → z.string()
 */

import { z } from "zod";

// ─────────────────────────────────────────────────────────────────────────────
// ProfileSchema
// Singleton record representing the professional whose value is being modelled.
// ─────────────────────────────────────────────────────────────────────────────
export const ProfileSchema = z.object({
  /** Primary key — CUID generated by Prisma */
  id: z.string(),

  /** Full display name */
  name: z.string(),

  /** Professional title or headline */
  title: z.string().nullable(),

  /** Short bio / executive summary */
  bio: z.string().nullable(),

  /** Primary contact email */
  email: z.string().email().nullable(),

  /** LinkedIn profile URL */
  linkedinUrl: z.string().url().nullable(),

  /** Personal or company website URL */
  websiteUrl: z.string().url().nullable(),

  /** Geographic location string (e.g. "San Francisco, CA") */
  location: z.string().nullable(),

  /** Years of total professional experience */
  yearsOfExperience: z.number().int().nullable(),

  /** Primary industry or sector */
  industry: z.string().nullable(),

  /** Freeform JSON blob for extensible metadata */
  metadata: z.unknown().nullable(),

  /** ISO-8601 creation timestamp */
  createdAt: z.string().datetime(),

  /** ISO-8601 last-update timestamp */
  updatedAt: z.string().datetime(),
});

// ─────────────────────────────────────────────────────────────────────────────
// ProofPointSchema
// Concrete, verifiable evidence items supporting claims in the value model.
// ─────────────────────────────────────────────────────────────────────────────
export const ProofPointSchema = z.object({
  id: z.string(),

  /** Foreign key → Profile */
  profileId: z.string(),

  /**
   * Category of proof: e.g. "achievement", "testimonial", "certification",
   * "publication", "award", "case_study"
   */
  category: z.string(),

  /** Human-readable title */
  title: z.string(),

  /** Detailed description of the proof point */
  description: z.string().nullable(),

  /** Quantified impact statement (e.g. "Reduced churn by 22%") */
  impact: z.string().nullable(),

  /** Source URL, citation, or reference */
  source: z.string().nullable(),

  /** Calendar date when this proof point occurred (ISO date string) */
  occurredAt: z.string().datetime().nullable(),

  /** Whether this proof point has been independently verified */
  verified: z.boolean(),

  /** Freeform JSON blob for extensible metadata */
  metadata: z.unknown().nullable(),

  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});

// ─────────────────────────────────────────────────────────────────────────────
// CapabilitySchema
// A skill, competency, or area of expertise.
// ─────────────────────────────────────────────────────────────────────────────
export const CapabilitySchema = z.object({
  id: z.string(),

  /** Foreign key → Profile */
  profileId: z.string(),

  /** Capability name (e.g. "System Design", "Revenue Operations") */
  name: z.string(),

  /** Broader grouping (e.g. "Technical", "Leadership", "Domain") */
  category: z.string().nullable(),

  /** Narrative description of the capability */
  description: z.string().nullable(),

  /**
   * Proficiency level: "beginner" | "intermediate" | "advanced" | "expert"
   * Stored as string to allow future extension without migration.
   */
  proficiencyLevel: z.string().nullable(),

  /** Number of years this capability has been practiced */
  yearsOfExperience: z.number().int().nullable(),

  /** Whether this is highlighted as a core/primary capability */
  isPrimary: z.boolean(),

  /** Display order for UI rendering */
  sortOrder: z.number().int(),

  /** Freeform JSON blob for extensible metadata */
  metadata: z.unknown().nullable(),

  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});

// ─────────────────────────────────────────────────────────────────────────────
// OutcomeSchema
// A result, deliverable, or impact produced — the "so what" of the value model.
// ─────────────────────────────────────────────────────────────────────────────
export const OutcomeSchema = z.object({
  id: z.string(),

  /** Foreign key → Profile */
  profileId: z.string(),

  /** Short title of the outcome */
  title: z.string(),

  /** Detailed description */
  description: z.string().nullable(),

  /**
   * Outcome type: "business", "technical", "personal", "team", "customer"
   */
  outcomeType: z.string().nullable(),

  /** Quantified result where applicable (e.g. "$2M ARR added") */
  quantifiedResult: z.string().nullable(),

  /** Timeframe over which the outcome was achieved */
  timeframe: z.string().nullable(),

  /** Organisation or client context */
  context: z.string().nullable(),

  /** Display order for UI rendering */
  sortOrder: z.number().int(),

  /** Freeform JSON blob for extensible metadata */
  metadata: z.unknown().nullable(),

  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});

// ─────────────────────────────────────────────────────────────────────────────
// MetricSchema
// A quantified measurement supporting an outcome or capability claim.
// ─────────────────────────────────────────────────────────────────────────────
export const MetricSchema = z.object({
  id: z.string(),

  /** Foreign key → Profile */
  profileId: z.string(),

  /** Optional foreign key → Outcome (metric may belong to an outcome) */
  outcomeId: z.string().nullable(),

  /** Metric label (e.g. "Monthly Active Users", "Net Revenue Retention") */
  name: z.string(),

  /** Numeric value */
  value: z.number(),

  /** Unit of measure (e.g. "%", "USD", "count", "x") */
  unit: z.string().nullable(),

  /**
   * Direction of improvement: "increase" | "decrease" | "maintain"
   * Allows rendering arrows/indicators correctly.
   */
  direction: z.string().nullable(),

  /** Baseline value before the change (for delta metrics) */
  baselineValue: z.number().nullable(),

  /** Target or goal value */
  targetValue: z.number().nullable(),

  /** Time period the metric covers (e.g. "Q3 2023", "FY2022") */
  period: z.string().nullable(),

  /** Category grouping for the metric (e.g. "Revenue", "Efficiency") */
  category: z.string().nullable(),

  /** Freeform JSON blob for extensible metadata */
  metadata: z.unknown().nullable(),

  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});

// ─────────────────────────────────────────────────────────────────────────────
// DifferentiatorSchema
// A competitive advantage or unique selling point.
// ─────────────────────────────────────────────────────────────────────────────
export const DifferentiatorSchema = z.object({
  id: z.string(),

  /** Foreign key → Profile */
  profileId: z.string(),

  /** Short statement of the differentiator */
  title: z.string(),

  /** Detailed explanation of why this is a differentiator */
  description: z.string().nullable(),

  /**
   * Type: "technical", "domain", "network", "track_record", "methodology",
   * "combination"
   */
  differentiatorType: z.string().nullable(),

  /** Who this differentiator matters to (target persona / role) */
  targetAudience: z.string().nullable(),

  /** Relative strength score 1–10 */
  strengthScore: z.number().int().nullable(),

  /** Whether this is a primary/headline differentiator */
  isPrimary: z.boolean(),

  /** Display order for UI rendering */
  sortOrder: z.number().int(),

  /** Freeform JSON blob for extensible metadata */
  metadata: z.unknown().nullable(),

  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});

// ─────────────────────────────────────────────────────────────────────────────
// ValuePropSchema
// A synthesised value proposition statement targeting a specific context.
// ─────────────────────────────────────────────────────────────────────────────
export const ValuePropSchema = z.object({
  id: z.string(),

  /** Foreign key → Profile */
  profileId: z.string(),

  /** Headline value proposition statement */
  headline: z.string(),

  /** Full narrative value proposition */
  body: z.string().nullable(),

  /** Target role, persona, or company type this prop is crafted for */
  targetPersona: z.string().nullable(),

  /** Job-to-be-done this prop addresses */
  jobToBeDone: z.string().nullable(),

  /**
   * Channel where this prop is intended to be used:
   * "linkedin_summary", "cv_summary", "pitch_deck", "cover_letter", "email"
   */
  channel: z.string().nullable(),

  /** Tone: "formal", "conversational", "technical", "executive" */
  tone: z.string().nullable(),

  /** Whether this is the primary/default value prop */
  isPrimary: z.boolean(),

  /** AI generation confidence score 0.0–1.0 */
  confidenceScore: z.number().nullable(),

  /** Version number for tracking iterations */
  version: z.number().int(),

  /** Freeform JSON blob for extensible metadata */
  metadata: z.unknown().nullable(),

  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});

// ─────────────────────────────────────────────────────────────────────────────
// ArtifactSchema
// A file, link, or document asset attached to the value model.
// ─────────────────────────────────────────────────────────────────────────────
export const ArtifactSchema = z.object({
  id: z.string(),

  /** Foreign key → Profile */
  profileId: z.string(),

  /** Human-readable name for the artifact */
  name: z.string(),

  /**
   * Artifact type: "resume", "portfolio", "case_study", "reference",
   * "certification", "publication", "video", "other"
   */
  artifactType: z.string(),

  /** Public or internal URL to the artifact */
  url: z.string().url().nullable(),

  /** File size in bytes (null for link-type artifacts) */
  fileSizeBytes: z.number().int().nullable(),

  /** MIME type (e.g. "application/pdf", "image/png") */
  mimeType: z.string().nullable(),

  /** Brief description of the artifact contents */
  description: z.string().nullable(),

  /** Whether this artifact is publicly shareable */
  isPublic: z.boolean(),

  /** Freeform JSON blob for extensible metadata */
  metadata: z.unknown().nullable(),

  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});

// ─────────────────────────────────────────────────────────────────────────────
// AiCallSchema
// Audit log record for every AI (LLM) invocation made by the system.
// ─────────────────────────────────────────────────────────────────────────────
export const AiCallSchema = z.object({
  id: z.string(),

  /** Foreign key → Profile (which profile triggered this call) */
  profileId: z.string(),

  /** AI provider name (e.g. "anthropic", "openai") */
  provider: z.string(),

  /** Model identifier (e.g. "claude-3-5-sonnet-20241022") */
  model: z.string(),

  /**
   * Logical operation this call was for:
   * "extract_proof_points", "generate_value_prop", "enrich_capability", etc.
   */
  operation: z.string(),

  /** Raw prompt / messages sent to the AI (stored as JSON) */
  promptSnapshot: z.unknown().nullable(),

  /** Raw completion response from the AI (stored as JSON) */
  responseSnapshot: z.unknown().nullable(),

  /** Number of tokens in the prompt */
  inputTokens: z.number().int().nullable(),

  /** Number of tokens in the completion */
  outputTokens: z.number().int().nullable(),

  /** Estimated cost of this call in USD */
  costUsd: z.number().nullable(),

  /** HTTP status or provider error code if the call failed */
  errorCode: z.string().nullable(),

  /** Human-readable error message */
  errorMessage: z.string().nullable(),

  /** Duration of the AI call in milliseconds */
  durationMs: z.number().int().nullable(),

  /** Whether the call succeeded */
  success: z.boolean(),

  createdAt: z.string().datetime(),
});

// ─────────────────────────────────────────────────────────────────────────────
// TypeScript type aliases — inferred from Zod schemas
// Use these types in function signatures, props, and state throughout the app.
// ─────────────────────────────────────────────────────────────────────────────

export type Profile = z.infer<typeof ProfileSchema>;
export type ProofPoint = z.infer<typeof ProofPointSchema>;
export type Capability = z.infer<typeof CapabilitySchema>;
export type Outcome = z.infer<typeof OutcomeSchema>;
export type Metric = z.infer<typeof MetricSchema>;
export type Differentiator = z.infer<typeof DifferentiatorSchema>;
export type ValueProp = z.infer<typeof ValuePropSchema>;
export type Artifact = z.infer<typeof ArtifactSchema>;
export type AiCall = z.infer<typeof AiCallSchema>;

// ─────────────────────────────────────────────────────────────────────────────
// ValueModel — composite aggregate type
//
// The complete in-memory representation of a profile's value model.
// API routes return this shape; client state is typed against it.
// ─────────────────────────────────────────────────────────────────────────────

export type ValueModel = {
  /** Core profile record */
  profile: Profile;

  /** All proof points belonging to this profile */
  proofPoints: ProofPoint[];

  /** All capabilities belonging to this profile */
  capabilities: Capability[];

  /** All outcomes belonging to this profile */
  outcomes: Outcome[];

  /** All metrics belonging to this profile */
  metrics: Metric[];

  /** All differentiators belonging to this profile */
  differentiators: Differentiator[];

  /** All value propositions belonging to this profile */
  valueProps: ValueProp[];

  /** All artifacts belonging to this profile */
  artifacts: Artifact[];
};

// ─────────────────────────────────────────────────────────────────────────────
// ValueModelSchema — Zod schema for the full aggregate (useful for API
// response validation in tests and client-side fetch wrappers)
// ─────────────────────────────────────────────────────────────────────────────

export const ValueModelSchema = z.object({
  profile: ProfileSchema,
  proofPoints: z.array(ProofPointSchema),
  capabilities: z.array(CapabilitySchema),
  outcomes: z.array(OutcomeSchema),
  metrics: z.array(MetricSchema),
  differentiators: z.array(DifferentiatorSchema),
  valueProps: z.array(ValuePropSchema),
  artifacts: z.array(ArtifactSchema),
});